var liveFlag=true;
if(!APPS_CHECKED){var beforeSizeMode,afterSizeMode;var mixType=document.getElementById("content").getAttribute("data-type")=="mix"?true:false;var commonObj=typeof commonObj!="undefined"?commonObj:undefined;(function(){if(!mixType){var commonJsonHttp=new XMLHttpRequest;var countryCode=typeof APPS_SITE_CODE!=="undefined"?APPS_SITE_CODE:document.querySelector("meta[name='sitecode']").getAttribute("content"),fileName="";commonJsonHttp.onreadystatechange=function(){if(this.readyState===4&&this.status===
200)commonObj=JSON.parse(this.responseText)};commonJsonHttp.open("GET","//images.samsung.com/is/content/samsung/p5/common/apps/json/common/common_"+countryCode+fileName+".json",true);commonJsonHttp.send()}})();(function appendCommonScript(){var fileName={"live":"apps_parser_xml","qa":"apps_parser_xml_qa"};var jsName=fileName.live;if(!liveFlag)jsName=fileName.qa;var scriptElem=document.createElement("script");scriptElem.type="text/javascript";scriptElem.src="/sec/static/evt/_script/mig/apps/"+jsName+".js";
scriptElem.className+="apps-js";var jqueryLoadCheck=setInterval(function(){if(typeof jQuery!="undefined"){document.body.appendChild(scriptElem);clearInterval(jqueryLoadCheck)}},10)})()}
if(APPS_CHECKED){var gifAnimate=function(){var gifImgSrcArray=[];jQueryOld(".section").each(function(){var _this=jQueryOld(this);var gifImgArray=[];_this.find("img").each(function(){if(!jQueryOld(this).parents(".slick-cloned").length){var __this=jQueryOld(this);var targetImg=__this.filter(function(){return jQueryOld(this).attr("src").indexOf("_ani.gif")>-1});if(targetImg.length){gifImgSrcArray.push(targetImg.attr("src"));gifImgArray.push(targetImg)}}});if(gifImgArray.length){jQueryOld.each(gifImgArray,
function(i,v){var target=v.parents(".slick-slider");if(target.length){var idx=v.parents(".slick-slide").attr("data-slick-index");target.on("afterChange",function(event,slick,currentSlide,nextSlide){if(currentSlide==idx)replaceSrc(v)})}});addViewportEvent({triggerPositionPercent:30,enter:function(){jQueryOld.each(gifImgArray,function(i,v){replaceSrc(v)})},leave:function(){}},_this)}});if(isMsie()){var replaceSrc$0=function(e){var imgSrc;if(toggleChecked){imgSrc=e.attr("src").split("?")[0];e.attr("src",
imgSrc+"?"+newTime);toggleChecked=false}else{imgSrc=e.attr("src").split("?")[0];e.attr("src",imgSrc+"?"+newTime2);toggleChecked=true}};var newTime=(new Date).getMilliseconds();var newTime2=newTime+1;var toggleChecked=true;var replaceGifImgSrcArray=[];jQueryOld.each(gifImgSrcArray,function(i,v){replaceGifImgSrcArray.push(v+"?"+newTime);replaceGifImgSrcArray.push(v+"?"+newTime2)});preloading(replaceGifImgSrcArray)}else var replaceSrc$1=function(e){var imgSrc;if(e.attr("src").indexOf("?")>-1)imgSrc=
e.attr("src").split("?")[0];else imgSrc=e.attr("src").replace(".gif",".gif?cash");e.attr("src",imgSrc)};function preloading(imageArray){var n=imageArray.length;for(var i=0;i<n;i++){var img=new Image;img.src=imageArray[i]}}};var imgSrcReplaceQa=function(target){var _hrefCheck=location.href.indexOf("www.samsung.com")>-1?false:true;if(_hrefCheck){var _thisApps=jQueryOld(document).find("#content, #apps_floating"),qaPath="/qa",qaUrl,checkKeyword=["/star","/crown","/beyond","/davinci","/hubble","/akm_images",
"/hero"],aemUrl="/is/image/";if(target)_thisApps=target;_thisApps.find("img, video source").each(function(){var _this=jQueryOld(this);var initCheck=false;jQueryOld.each(checkKeyword,function(i,v){jQueryOld.each(["src","data-src-pc","data-src-mobile","data-role-img"],function(j,w){if(_this.attr(w))if(_this.attr(w).indexOf(v)>-1)initCheck=true});if(initCheck){var dataObj=_this.data();for(var key in dataObj){if(typeof dataObj[key]=="string"&&dataObj[key].indexOf(qaPath)===-1)dataObj[key]=dataObj[key].replace(v,
v+qaPath);if(key=="srcPc")_this.attr("data-src-pc",dataObj[key]);else if(key=="srcMobile")_this.attr("data-src-mobile",dataObj[key]);else if(key=="roleImg")_this.attr("data-role-img",dataObj[key])}if(_this.attr("src").indexOf(qaPath)===-1){qaUrl=_this.attr("src").replace(v,v+qaPath);_this.attr("src",qaUrl)}}})});_thisApps.find("[data-vid-data]").each(function(){var _this=jQueryOld(this),_data=_this.data("vid-data"),_vidUrl=_data.videoURL,_vidQaUrl="";if(_vidUrl!==undefined){jQueryOld.each(checkKeyword,
function(i,v){if(_vidUrl.indexOf(qaPath)===-1){_vidQaUrl=_vidUrl.replace(v,v+qaPath);_data.videoURL=_vidQaUrl}});_this.attr("data-vid-data",JSON.stringify(_data))}})}};var pdpImgReplace=function(){var $pdp=jQueryOld(".create-pdp"),$figure=$pdp.find("figure img"),resizeFlag="",winHoriz=window.innerWidth!==undefined?window.innerWidth:document.documentElement.clientWidth;if(winHoriz>768)$figure.each(function(){jQueryOld(this).attr("src",jQueryOld(this).data("src-pc"))});else $figure.each(function(){jQueryOld(this).attr("src",
jQueryOld(this).data("src-mobile"))})};var resize=function(func){var isMobile=jQueryOld.browser.mobile,isPoorBrowser=jQueryOld.browser.ie&&9>jQueryOld.browser.ie,areaWidth=0,areaHeight=0,prevSizeMode=-1,sizeModeinit=0,scrollBarWidth=0,resizeFunctions=[];if(typeof func=="function"){this.resizeFunctions.push(func);return this}var documentElement=document.documentElement,width,height,sizeMode;width=documentElement.clientWidth;if(isPoorBrowser)width=Math.max(document.getElementById("wrap").offsetWidth,
width);height=jQueryOld(window).height();if(func!==true)if(!jQueryOld.browser.mobile&&width==areaWidth&&height==areaHeight)return;else if(jQueryOld.browser.mobile&&width==areaWidth)return;var scrollBarWidth;var windowSize=window.innerWidth!=undefined?window.innerWidth:jQueryOld(window).innerWidth()+17;if(jQueryOld.browser.mobile)scrollBarWidth=0;else scrollBarWidth=17;sizeMode=windowSize>1440?3:windowSize>768?2:1;prevSizeMode=sizeModeinit;if(sizeMode!=sizeModeinit)sizeModeinit=sizeMode;areaWidth=
width;areaHeight=height;if(resizeFunctions.length)jQueryOld.each(resizeFunctions,function(){this()});pdpImgReplace()};var addViewportEvent=function(param,target){var events="scroll.addViewportEvent load.addViewportEvent resize.addViewportEvent";param=jQueryOld.extend({parent:window,a11y:false,triggerPosition:false,triggerPositionPercent:false,enter:false,leave:false,progress:false,visiblePercent:false,visible:false,invisible:false,fullVisible:false},param||{});if(typeof(param.triggerPosition&&param.triggerPositionPercent)==
"number")return true;var methods=jQueryOld.fn.extend({destroy:function(){jQueryOld(param.parent).off(events)}});return target.each(function(idx,obj){var isEnter=false;var isVisible=false;var isActive=false;var isFullVisible=false;var visiblePercent=0;var parent=param.parent;jQueryOld(parent).on(events,function(){var returnValue={Height:jQueryOld(obj).outerHeight(),ViewportHeight:jQueryOld(parent).height(),ScrollTop:jQueryOld(document).scrollTop(),OffsetTop:jQueryOld(obj).offset().top};var visiblePerTopPercent=
((returnValue.ScrollTop+returnValue.ViewportHeight-returnValue.OffsetTop)/returnValue.Height*100).toFixed(2);var visiblePerBottomPercent=-((returnValue.ScrollTop-returnValue.OffsetTop-returnValue.Height)/returnValue.Height*100).toFixed(2);var viewPortPosition=returnValue.OffsetTop-returnValue.ScrollTop-param.triggerPosition;var viewPortPositionPercent=(viewPortPosition/returnValue.ViewportHeight*100-param.triggerPositionPercent).toFixed(2);isVisible=visiblePerTopPercent>=0&&visiblePerBottomPercent>=
0;if(viewPortPositionPercent>=50)viewPortPositionPercent=50;else if(viewPortPositionPercent<=-50)viewPortPositionPercent=-50;if(isVisible&&visiblePerTopPercent<=100)visiblePercent=visiblePerTopPercent;else if(isVisible&&visiblePerBottomPercent<=100)visiblePercent=visiblePerBottomPercent;else if(isVisible)visiblePercent=100;else visiblePercent=0;if(isVisible){obj.isVisible=isVisible;obj.isEnter=isEnter;obj.viewPortPositionPercent=viewPortPositionPercent;obj.viewPortPosition=viewPortPosition;obj.visiblePercent=
visiblePercent}if(isVisible){if(!isEnter&&(param.triggerPositionPercent!==false&&viewPortPositionPercent<=0)||param.triggerPosition&&viewPortPosition<=0){jQueryOld(obj).trigger("enter");if(jQueryOld.isFunction(param.enter))param.enter()}if(isEnter&&(param.triggerPositionPercent!==false&&viewPortPositionPercent>0)||param.triggerPosition&&viewPortPosition>0){jQueryOld(obj).trigger("leave");if(jQueryOld.isFunction(param.leave))param.leave()}if(jQueryOld.isFunction(param.progress)){if(param.triggerPositionPercent)param.progress(Number(viewPortPositionPercent),
returnValue);if(param.triggerPosition)param.progress(Number(viewPortPosition),returnValue)}}if(!isActive&&visiblePercent>0){jQueryOld(obj).trigger("visible");if(jQueryOld.isFunction(param.visible))param.visible()}if(isActive&&visiblePercent==0){jQueryOld(obj).trigger("invisible");if(jQueryOld.isFunction(param.invisible))param.invisible();jQueryOld(obj).trigger("leave");if(jQueryOld.isFunction(param.leave))param.leave()}if(!isFullVisible&&visiblePercent==100){jQueryOld(obj).trigger("fullVisible");
if(jQueryOld.isFunction(param.fullVisible))param.fullVisible()}if(jQueryOld.isFunction(param.visiblePercent))param.visiblePercent(Number(visiblePercent),returnValue);isActive=visiblePercent!=0;isEnter=param.triggerPositionPercent&&viewPortPositionPercent<=0&&isVisible||param.triggerPosition&&viewPortPosition<=0&&isVisible;isFullVisible=visiblePercent>=100})})};var isMsie=function(){if(navigator.userAgent.toLowerCase().indexOf("msie")>-1||navigator.userAgent.toLowerCase().indexOf("trident/")>-1)return true;
return false};var layerAria=function(value){jQueryOld("#header").attr("aria-hidden",value);jQueryOld(".cm-g-breadcrumb").attr("aria-hidden",value);jQueryOld("#footer").attr("aria-hidden",value);jQueryOld("#oo_tab").attr("aria-hidden",value);jQueryOld(".s-btn-gotop").attr("aria-hidden",value)};if(!liveFlag){var changeCss=function(){var target=document.getElementsByClassName("apps-css");for(var i=0;i<target.length;i++){var thisHref=target[i].getAttribute("href");var fileName=thisHref.split("/").pop().split(".")[0];
var path=thisHref.indexOf("service/")>-1?"service/":"";if(fileName.indexOf("_qa")<0)target[i].setAttribute("href","//images.samsung.com/is/content/samsung/p5/common/apps/css/"+path+fileName+"_qa.css")}};changeCss()}jQueryOld.browser={};(function(){jQueryOld.browser.mobile=false;jQueryOld.browser.ie=false;jQueryOld.browser.version=0;if(navigator.userAgent.match(/MSIE ([0-9]+)\./)){jQueryOld.browser.ie=true;jQueryOld.browser.version=RegExp.$1}else if(navigator.userAgent.match(/Mobile ([0-9]+)\./)){jQueryOld.browser.mobile=
true;jQueryOld.browser.version=RegExp.$1}})();eiwafDevice={TYPE_DESKTOP:"desktop",TYPE_PHONE:"phone",TYPE_TABLET:"tablet",agent:{_mobile:/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/i.test(window.navigator.userAgent),_tablet:/iPad|tablet/i.test(window.navigator.userAgent)},detect:function(){var _userAgent=navigator.userAgent.toLowerCase();_html=jQueryOld(document.documentElement);if(_userAgent.search("sm-")>
-1){_html.addClass("samsung-device");if(this.agent.mobile)_html.addClass("samsung-mobile-device")}if(this.type)return;if(this.agent._mobile){if(_userAgent.search("android")>-1)if(_userAgent.search("mobile")==-1)this.type=this.TYPE_TABLET;if(!this.type)this.type=this.TYPE_PHONE}if(this.agent._tablet)this.type=this.TYPE_TABLET;if(!this.type)this.type=this.TYPE_DESKTOP;switch(this.type){case "phone":_html.addClass("apps-device-phone");break;case "tablet":_html.addClass("apps-device-tablet");break;case "desktop":_html.addClass("apps-device-desktop");
break;default:break}}};deepLink={oneUI:{deepUrl:"voc://view/notice",redirectUrl:"https://play.google.com/store/apps/details?id=com.samsung.android.voc",init:function(){var targetLink=jQueryOld("[id*='deeplink']").find("a");targetLink.on("click",function(e){if(jQueryOld("meta[name='sitecode']").attr("content")=="latin_en"||jQueryOld("meta[name='sitecode']").attr("content")=="latin")deepLink.oneUI.deepUrl="voc://view/main?tab=NEWSNTIPS";var odcPop=window.open(deepLink.oneUI.deepUrl);var check_count=
0;var popupCheck=setInterval(function(){if(odcPop.closed)clearInterval(popupCheck);else{if(check_count==3){clearInterval(popupCheck);check_count=0;odcPop.location.href=deepLink.oneUI.redirectUrl}check_count++}},200);e.preventDefault()})}},init:function(){deepLink.oneUI.init()}};floating={serviceFloatingBar:{elem:{_toggleAlt:null,_resizeIdx:0},grid:function(_country){var _floatingJson=commonObj.floating,_floatingJsonCommon=_floatingJson.common,_floatingCommonTitle=_floatingJsonCommon.title,_floatingCommonAlt=
_floatingJsonCommon.alt,_floatingCommonToggle=_floatingJsonCommon.toggle,_floatingCommonImgPath=_floatingJsonCommon.imgPath,_floatingHtml="",_floatingServiceName=APPS_SERVICE_NAME=="penup"?"pen_up":APPS_SERVICE_NAME.replace(/-/gi,"_").replace(/ /gi,"_"),_floatingServices=_floatingJson.services;_floatingHtml+="<div id='apps_floating' class='apps_rawcode'>";_floatingHtml+="<div class='navi_wrap'>";_floatingHtml+="<div class='navi_section'>";_floatingHtml+="<div class='navi_header'>";_floatingHtml+=
"<div class='toggle_btn_box'>";_floatingHtml+="<a href='#' class='toggle_btn' data-omni-type='microsite_contentinter' data-omni='apps:"+_floatingServiceName+":service_open'>";_floatingHtml+="<span data-key='apps.services.title'>"+_floatingCommonTitle+"</span><span class='blind' data-key='apps.services.open'>"+_floatingCommonToggle[0]+"</span>";_floatingHtml+="</a>";_floatingHtml+="</div>";_floatingHtml+="<div class='navi_btn_list'>";_floatingHtml+="<div class='navi_btn_inner'>";_floatingHtml+="<a href='/"+
_country+"/apps' data-omni-type='microsite_contentinter' data-omni='apps:"+_floatingServiceName+":floating bar:go to apps landing page'>";_floatingHtml+="<img src='"+_floatingCommonImgPath+"' alt='"+_floatingCommonAlt+"' data-key='apps.services.landing_img-alt'>";_floatingHtml+="</a>";_floatingHtml+="</div>";_floatingHtml+="</div>";_floatingHtml+="</div>";_floatingHtml+="<div class='navi_contents'>";_floatingHtml+="<div class='navi_inner'>";_floatingHtml+="<ul class='navi_service_list'>";for(var _key in _floatingServices){var _serviceJson=
_floatingServices[_key],_serviceLink=_serviceJson.href,_serviceImgPath=_serviceJson.imgPath,_serviceTitle=_serviceJson.title,_serviceName=_key==="pen-up"?"pen_up":_key.replace(/-/gi,"_").replace(/ /gi,"_"),_blank="";if(typeof _serviceJson.blank!=="undefined")_blank=_serviceJson.blank;_floatingHtml+="<li data-role-name='"+_key+"'>";_floatingHtml+="<a href='"+_serviceLink+"' "+(_blank.length>0?"target='_blank'":"")+" data-omni-type='microsite_contentinter' data-omni='apps:"+_floatingServiceName+":service_"+
_serviceName+"' "+(_serviceJson.blank=="Y"?"target='_blank'":"")+">";_floatingHtml+="<figure><img src='//images.samsung.com/is/image/samsung/p5/common/apps/akm_images/common/blank.gif' data-role-img='"+_serviceImgPath+"' alt=''></figure>";_floatingHtml+="<em class='tit' data-key='apps.landing.services."+_serviceName.replace(/ /gi,"_")+".title'>"+_serviceTitle+"</em>";_floatingHtml+="</a>";_floatingHtml+="</li>"}_floatingHtml+="</ul></div></div></div></div></div>";jQueryOld(document).find("#content").prepend(_floatingHtml);
floating.serviceFloatingBar.elem._toggleAlt=_floatingCommonToggle;var firstTarget=jQueryOld("#apps_floating .toggle_btn");var lastTarget=jQueryOld("#apps_floating .navi_service_list li:last-child a");var logoTarget=jQueryOld(document).find(".gb-gnb__bar-inner > a:first-child");firstTarget.on({"keydown":function(e){if(e.shiftKey)if((e.which==9||e.keyCode==9)&&jQueryOld(window).scrollTop()!==0&&firstTarget.is(".is_open")===true){e.preventDefault();lastTarget.focus()}}});lastTarget.on({"keydown":function(e){if(e.shiftKey);
else if(e.which==9||e.keyCode==9)if(jQueryOld(window).scrollTop()!==0&&firstTarget.is(".is_open")===true){e.preventDefault();firstTarget.focus()}else if(jQueryOld(window).scrollTop()===0&&firstTarget.is(".is_open")===true){e.preventDefault();logoTarget.focus()}}});logoTarget.on({"keydown":function(e){if(e.shiftKey)if((e.which==9||e.keyCode==9)&&jQueryOld(window).scrollTop()===0&&firstTarget.is(".is_open")===true){e.preventDefault();lastTarget.focus()}}})},click:function(){var _naviWrap=jQueryOld(document).find(".apps_rawcode .navi_wrap"),
_naviContents=_naviWrap.find(".navi_contents"),_naviServiceList=_naviWrap.find(".navi_service_list > li"),_naviServiceListLength=_naviServiceList.length,_idx=0,_idxArr=randomFnc(_naviServiceListLength),_bounceSetTimeFnc=null;jQueryOld(document).on("click",".apps_rawcode .navi_wrap .toggle_btn",function(e){e.preventDefault();var _tagging=jQueryOld(this).data("omni"),_replaceTagging="";jQueryOld(this).toggleClass("is_open");if(_naviContents.find("img").attr("src").indexOf("blank.gif")>-1)_naviContents.find("img").each(function(){var _src=
jQueryOld(this).data("role-img");jQueryOld(this).attr("src",_src)});clearTimeout(_bounceSetTimeFnc);if(jQueryOld(this).is(".is_open")){_idxArr=randomFnc(_naviServiceListLength);_naviContents.addClass("is_open");jQueryOld("html").css("overflow","hidden");bounceMotion(_idx,20,true);_replaceTagging=_tagging.replace("_open","_close");jQueryOld(this).attr("data-omni",_replaceTagging);jQueryOld(this).find(".blind").text(floating.serviceFloatingBar.elem._toggleAlt[1]);jQueryOld(this).find(".blind").attr("data-key",
jQueryOld(this).find(".blind").attr("data-key").replace(".open",".close"));layerAria(true);if(!_naviWrap.hasClass("fixed"))jQueryOld("#header").attr("aria-hidden",false);jQueryOld("#content .par").attr("aria-hidden",true)}else{_naviContents.removeClass("is_open");_naviServiceList.removeClass("bounce");jQueryOld("html").removeAttr("style");_replaceTagging=_tagging.replace("_close","_open");jQueryOld(this).attr("data-omni",_replaceTagging);jQueryOld(this).find(".blind").text(floating.serviceFloatingBar.elem._toggleAlt[0]);
jQueryOld(this).find(".blind").attr("data-key",jQueryOld(this).find(".blind").attr("data-key").replace(".close",".open"));layerAria(false);jQueryOld("#content .par").attr("aria-hidden",false)}});function bounceMotion(_idx,_timer){if(_idx<_naviServiceListLength){_naviServiceList.eq(_idxArr[_idx]-1).addClass("bounce");_bounceSetTimeFnc=setTimeout(function(){bounceMotion(_idx+1,_timer)},_timer)}}function randomFnc(n){var ar=new Array;var temp;var rnum;for(var i=1;i<=n;i++)ar.push(i);for(var i=0;i<ar.length;i++){rnum=
Math.floor(Math.random()*n);temp=ar[i];ar[i]=ar[rnum];ar[rnum]=temp}return ar}if(jQueryOld(document).find(".mkt-anchor-navi").length>0)jQueryOld(".mkt-anchor-navi__anchor li a").on({"click":function(){if(window.innerWidth<=768){var _this=jQueryOld(this);setTimeout(function(){var target=_this.attr("href");var targetOffsetTop=jQueryOld(target).offset().top;var positionTop=targetOffsetTop-parseInt(jQueryOld(".navi_section").outerHeight());jQueryOld("body, html").stop().animate({scrollTop:positionTop},
500)},0)}}})},scroll:function(){if(jQueryOld(document).find("#apps_floating").length>0&&window.innerWidth<=768){var _stickyCheck=location.href.toLowerCase().indexOf("/bixby")>-1?true:false;var _windowTop=jQueryOld(window).scrollTop();var _gnbHeight=jQueryOld(document).find("#header").outerHeight();var _naviHeight=jQueryOld(document).find(".navi_header").outerHeight();if(_windowTop>=_gnbHeight)jQueryOld(document).find(".navi_wrap").addClass("fixed");else jQueryOld(document).find(".navi_wrap").removeClass("fixed");
if(_stickyCheck===true&&jQueryOld(document).find(".js-sticky-placeholder").length>0){var _bixbyTop=jQueryOld(document).find(".js-sticky-placeholder").offset().top;if(_windowTop>=_bixbyTop-_naviHeight)jQueryOld(document).find(".cl-g-sticky-navigation-text").addClass("apps-fixed");else jQueryOld(document).find(".cl-g-sticky-navigation-text").removeClass("apps-fixed")}}},resize:function(){var _siteCode=typeof APPS_SITE_CODE!=="undefined"?APPS_SITE_CODE:siteCode,_xmlDataCheck=typeof xmlData!=="undefined"?
true:false;if(floating.serviceFloatingBar.elem._resizeIdx>1&&_xmlDataCheck)if(jQueryOld(document).find("#apps_floating").length===0&&window.innerWidth<=768&&(_siteCode!=="au"&&_siteCode!=="fr"))this.grid(_siteCode);else{if(jQueryOld(document).find("#apps_floating").length>0&&window.innerWidth>768){var _tagging=jQueryOld(document).find("#apps_floating .toggle_btn").data("omni"),_replaceTagging="";_replaceTagging=_tagging.replace("_close","_open");if(jQueryOld(document).find(".js-sticky-placeholder").length>
0)jQueryOld(document).find(".cl-g-sticky-navigation-text").removeClass("apps-fixed");jQueryOld("html").removeAttr("style");jQueryOld(document).find("#apps_floating .toggle_btn .blind").text(floating.serviceFloatingBar.elem._toggleAlt[0]);jQueryOld(document).find("#apps_floating .toggle_btn").attr("data-omni",_replaceTagging);jQueryOld(document).find("#apps_floating *").removeClass("is_open");jQueryOld(document).find("#apps_floating *").removeClass("bounce")}}else floating.serviceFloatingBar.elem._resizeIdx=
floating.serviceFloatingBar.elem._resizeIdx+1},init:function(){var _appsFloatingCheck=jQueryOld(document).find("#apps_floating").length===0?true:false,_siteCode=APPS_SITE_CODE;if(_appsFloatingCheck){this.grid(_siteCode);this.click()}}}};jQueryOld(window).on(function(){imgSrcReplaceQa();gifAnimate();deepLink.init();if(jQueryOld("img[src$='.svg']").length>0)jQueryOld("img[src$='.svg']").attr("role","img");if(APPS_SERVICE_NAME==="bixby"&&(APPS_SITE_CODE==="mm"||APPS_SITE_CODE==="th")){var _discWrap=
jQueryOld(document).find(".cl-textbox__disclaimer.fs-disclaimer"),_title=APPS_SITE_CODE==="mm"?"SmartThings စာမျက်နှာသို့သွားပါ :ဝင်းဒိုးအသစ်တစ်ခုတွင် ဖွင့်ပါ":APPS_SITE_CODE==="th"?"ไปที่เพจ SmartThings : เปิดหน้าต่างใหม่":undefined;if(_discWrap.length>0&&_title!==undefined)_discWrap.each(function(){var _href=jQueryOld(this).find("a").attr("href");if(_href!==undefined)if(_href.indexOf("www.samsung.com/smartthings")>-1)jQueryOld(this).find("a").attr("title",_title)})}if(APPS_SITE_CODE==="th")setTimeout(function(){var _link=
jQueryOld(".apps a[href^='#'], #apps_floating a[href^='#'], .apps_cr a[href^='#']");_link.each(function(){if(jQueryOld(this).attr("href")!=="#search"&&jQueryOld(this).attr("href")!=="#section-deal"&&jQueryOld(this).attr("href")!=="#section-locally")jQueryOld(this).attr("href","javascript:void(0)")})},500);if(APPS_SITE_CODE==="ch"&&APPS_SERVICE_NAME==="samsung-kids"){var _faqBtn=document.querySelector("a[href='https://help.content.samsung.com/csweb/auth/gosupport.do?serviceCd=skidshome&_common_country=CH&_common_lang=de&chnlCd=WEB&targetUrl=/faq/searchFaq.do']");
_faqBtn.text="FAQ AUFRUFEN"}if(APPS_SITE_CODE==="n_africa"&&APPS_SERVICE_NAME==="samsung-kids"){var _faqBtn=document.querySelector("a[href='https://help.content.samsung.com/csweb/auth/gosupport.do?serviceCd=skidshome&_common_country=BJ&_common_lang=fr_fr&chnlCd=WEB&targetUrl=/faq/searchFaq.do']");var _faqDescText=_faqBtn.parentNode.previousElementSibling.querySelector(".cl-icons-texts-img__desc");_faqBtn.text="ACCÉDER À SAMSUNG KIDS";_faqDescText.innerHTML="Découvrez la nouvelle version de Mode Enfant avec Samsung Kids."}});
jQueryOld(window).scroll(function(){floating.serviceFloatingBar.scroll()});jQueryOld(window).resize(function(){resize();floating.serviceFloatingBar.resize()});jQueryOld(document).ready(function(){if(APPS_SERVICE_NAME=="smart switch")if(APPS_SITE_CODE==="gr"||APPS_SITE_CODE==="iran"||APPS_SITE_CODE==="th"){var target0306=jQueryOld(".cl-g-textbox").eq(2).find(".cl-textbox__text.contrast-target");var targetText0306=target0306.html().split("<br>")[1];target0306.html("<br>"+targetText0306).next(".cl-btn-inherit").hide()}if(APPS_SERVICE_NAME===
"samsung-kids-home")jQueryOld("html").addClass(APPS_SERVICE_NAME);eiwafDevice.detect();var _timer=0;var _jsonDataCheck=setInterval(function(){_timer=_timer+10;if(typeof commonObj!=="undefined"){clearInterval(_jsonDataCheck);floating.serviceFloatingBar.init()}else if(_timer>5E3){console.error("error json undefinded");clearInterval(_jsonDataCheck)}},10);if(APPS_SERVICE_NAME==="samsung-blockchain"){var _kvDiscWrap=jQueryOld(document).find("[id*='mobile_samsung'] .feature-benefit__disclaimer-wrap"),_kvTextWrap=
jQueryOld(document).find("[id*='mobile_samsung'] .feature-benefit__text");_kvTextWrap.append(_kvDiscWrap)}})}APPS_CHECKED=true;
