$(document).ready(function(){});
var plaza={searchByCityDtrtUrl:null,roomYn:null,isPlazaNm:null,setSearchCityDtrtData:function(searchType,cityCd,dtrtCd,defaultCd){if(searchType==="CITY")plaza.listPlazaSearchByCityDtrt(null,null,"CITY",plaza.roomYn,"cityList",null,defaultCd);else if(searchType==="DTRT")plaza.listPlazaSearchByCityDtrt(cityCd,null,"DTRT",plaza.roomYn,"dtrtList",null,defaultCd);else if(searchType==="PLAZA_NAME")plaza.listPlazaSearchByCityDtrt(cityCd,dtrtCd,null,plaza.roomYn,"plazaNmList",plaza.isPlazaNm,defaultCd)},
listPlazaSearchByCityDtrt:function(cityCd,dtrtCd,groupByVal,roomYn,target,plazaNm,defaultCd){var defaultNm="";var options={url:plaza.searchByCityDtrtUrl,data:{cityCd:cityCd,dtrtCd:dtrtCd,acdmYn:"Y",roomYn:roomYn,groupByVal:groupByVal},done:function(data){var html="";var item=data.list;var plazaNmList=data.plazaNmList;if(target==="cityList")plaza.getCityList(item,defaultCd,defaultNm);else if(target==="dtrtList")plaza.getDtrtList(item,defaultCd,defaultNm);if(plazaNm==="Y")plaza.getPlazaList(plazaNmList,
defaultCd,defaultNm);if(plaza.callback!=undefined)plaza.callback()}};ajax.call(options)},getCityList:function(item,defaultCd,defaultNm){var html='<li id="type-all" role="option" type="city-all" class="droplist-item">전체</li>';for(var j in item)if(defaultCd!=="undefined"&&defaultCd!=""&&defaultCd==item[j].cityCd){defaultNm=item[j].cityDtlNm;html+='<li id="type-'+item[j].cityCd+'" role="option" type="city" class="droplist-item focused" city-cd="'+item[j].cityCd+'" data-cd="'+item[j].cityCd+'" aria-selected="selected">'+
item[j].cityDtlNm+"</li>"}else html+='<li id="type-'+item[j].cityCd+'" role="option" type="city" class="droplist-item" city-cd="'+item[j].cityCd+'" data-cd="'+item[j].cityCd+'">'+item[j].cityDtlNm+"</li>";if(defaultCd!=="undefined"&&defaultCd!=""&&defaultNm!=""){$(".cityList button").text(defaultNm);$(".cityList button").addClass("selected");$(".cityList ul").attr("aria-activedescendant","type-"+defaultCd)}else{$(".cityList button").text($("#droplistTitle01").text());$(".cityList ul").attr("aria-activedescendant",
"type-All")}$(".cityList ul").html("");$(".cityList ul").append(html)},getDtrtList:function(item,defaultCd,defaultNm){var html='<li id="type-all" role="option" type="dtrt-all" class="droplist-item">전체</li>';for(var i in item)if(defaultCd!=="undefined"&&defaultCd!=""&&defaultCd==item[i].dtrtCd){defaultNm=item[i].dtrtDtlNm;html+='<li id="type-'+item[i].dtrtCd+'" role="option" type="dtrt" class="droplist-item focused" city-cd="'+item[i].cityCd+'" dtrt-cd="'+item[i].dtrtCd+'" data-cd="'+item[i].dtrtCd+
'" aria-selected="selected">'+item[i].dtrtDtlNm+"</li>"}else html+='<li id="type-'+item[i].dtrtCd+'" role="option" type="dtrt" class="droplist-item" city-cd="'+item[i].cityCd+'" dtrt-cd="'+item[i].dtrtCd+'" data-cd="'+item[i].dtrtCd+'">'+item[i].dtrtDtlNm+"</li>";if(defaultCd!=="undefined"&&defaultCd!=""&&defaultNm!=""){$(".dtrtList button").text(defaultNm);$(".dtrtList button").addClass("selected");$(".dtrtList ul").attr("aria-activedescendant","type-"+defaultCd)}else{$(".dtrtList button").text($("#droplistTitle02").text());
$(".dtrtList ul").attr("aria-activedescendant","type-All")}$(".dtrtList ul").html("");$(".dtrtList ul").append(html)},getPlazaList:function(plazaNmList,defaultCd,defaultNm){var plazaNmhtml="";plazaNmhtml+='<li id="type-all" role="option" type="plaza-all" class="droplist-item">전체</li>';for(var k in plazaNmList)if(defaultCd!=="undefined"&&defaultCd!=""&&defaultCd==plazaNmList[k].shopNo){defaultNm=plazaNmList[k].plazaNm;plazaNmhtml+='<li id="type-'+plazaNmList[k].plazaNo+'" role="option" class="droplist-item focused" data-cd="'+
plazaNmList[k].plazaNo+'" shopNo="'+plazaNmList[k].shopNo+'" aria-selected="selected">'+plazaNmList[k].plazaNm+"</li>"}else plazaNmhtml+='<li id="type-'+plazaNmList[k].plazaNo+'" role="option" class="droplist-item" data-cd="'+plazaNmList[k].plazaNo+'" shopNo="'+plazaNmList[k].shopNo+'">'+plazaNmList[k].plazaNm+"</li>";if(defaultCd!=="undefined"&&defaultCd!=""&&defaultNm!=""){$(".plazaNmList button").text(defaultNm);$(".plazaNmList button").addClass("selected");$(".plazaNmList ul").attr("aria-activedescendant",
"type-"+defaultCd)}else{$(".plazaNmList button").text($("#droplistTitle03").text());$(".plazaNmList ul").attr("aria-activedescendant","type-All")}$(".plazaNmList ul").html("");$(".plazaNmList ul").append(plazaNmhtml)}};var PlazaRoomSharedDTO=function(sido,gugun,startdt,vkbur,storeNm,page){if(sido!="")this.sido=sido;if(gugun!="")this.gugun=gugun;if(startdt!="")this.startdt=startdt;if(vkbur!="")this.vkbur=vkbur;if(storeNm!="")this.storeNm=storeNm;if(page!="")this.page=page};
