var CryptoJS=CryptoJS||function(t,e){var r={},i=r.lib={},n=i.Base=function(){function t(){}return{extend:function(e){t.prototype=this;var r=new t;return e&&r.mixIn(e),r.$super=this,r},create:function(){var t=this.extend();return t.init.apply(t,arguments),t},init:function(){},mixIn:function(t){for(var e in t)t.hasOwnProperty(e)&&(this[e]=t[e]);t.hasOwnProperty("toString")&&(this.toString=t.toString)},clone:function(){return this.$super.extend(this)}}}(),o=i.WordArray=n.extend({init:function(t,r){t=
this.words=t||[],this.sigBytes=r!=e?r:4*t.length},toString:function(t){return(t||c).stringify(this)},concat:function(t){var e=this.words,r=t.words,i=this.sigBytes,t=t.sigBytes;if(this.clamp(),i%4)for(var n=0;t>n;n++)e[i+n>>>2]|=(r[n>>>2]>>>24-8*(n%4)&255)<<24-8*((i+n)%4);else if(65535<r.length)for(n=0;t>n;n+=4)e[i+n>>>2]=r[n>>>2];else e.push.apply(e,r);return this.sigBytes+=t,this},clamp:function(){var e=this.words,r=this.sigBytes;e[r>>>2]&=4294967295<<32-8*(r%4),e.length=t.ceil(r/4)},clone:function(){var t=
n.clone.call(this);return t.words=this.words.slice(0),t},random:function(e){for(var r=[],i=0;e>i;i+=4)r.push(4294967296*t.random()|0);return o.create(r,e)}}),s=r.enc={},c=s.Hex={stringify:function(t){for(var e=t.words,t=t.sigBytes,r=[],i=0;t>i;i++){var n=e[i>>>2]>>>24-8*(i%4)&255;r.push((n>>>4).toString(16)),r.push((15&n).toString(16))}return r.join("")},parse:function(t){for(var e=t.length,r=[],i=0;e>i;i+=2)r[i>>>3]|=parseInt(t.substr(i,2),16)<<24-4*(i%8);return o.create(r,e/2)}},a=s.Latin1={stringify:function(t){for(var e=
t.words,t=t.sigBytes,r=[],i=0;t>i;i++)r.push(String.fromCharCode(e[i>>>2]>>>24-8*(i%4)&255));return r.join("")},parse:function(t){for(var e=t.length,r=[],i=0;e>i;i++)r[i>>>2]|=(255&t.charCodeAt(i))<<24-8*(i%4);return o.create(r,e)}},f=s.Utf8={stringify:function(t){try{return decodeURIComponent(escape(a.stringify(t)))}catch(e$0){throw Error("Malformed UTF-8 data");}},parse:function(t){return a.parse(unescape(encodeURIComponent(t)))}},h=i.BufferedBlockAlgorithm=n.extend({reset:function(){this._data=
o.create(),this._nDataBytes=0},_append:function(t){"string"==typeof t&&(t=f.parse(t)),this._data.concat(t),this._nDataBytes+=t.sigBytes},_process:function(e){var r=this._data,i=r.words,n=r.sigBytes,s=this.blockSize,c=n/(4*s),c=e?t.ceil(c):t.max((0|c)-this._minBufferSize,0),e=c*s,n=t.min(4*e,n);if(e){for(var a=0;e>a;a+=s)this._doProcessBlock(i,a);a=i.splice(0,e),r.sigBytes-=n}return o.create(a,n)},clone:function(){var t=n.clone.call(this);return t._data=this._data.clone(),t},_minBufferSize:0});i.Hasher=
h.extend({init:function(){this.reset()},reset:function(){h.reset.call(this),this._doReset()},update:function(t){return this._append(t),this._process(),this},finalize:function(t){return t&&this._append(t),this._doFinalize(),this._hash},clone:function(){var t=h.clone.call(this);return t._hash=this._hash.clone(),t},blockSize:16,_createHelper:function(t){return function(e,r){return t.create(r).finalize(e)}},_createHmacHelper:function(t){return function(e,r){return u.HMAC.create(t,r).finalize(e)}}});var u=
r.algo={};return r}(Math);
!function(){var t=CryptoJS,e=t.lib.WordArray;t.enc.Base64={stringify:function(t){var e=t.words,r=t.sigBytes,i=this._map;t.clamp();for(var t=[],n=0;r>n;n+=3)for(var o=(e[n>>>2]>>>24-8*(n%4)&255)<<16|(e[n+1>>>2]>>>24-8*((n+1)%4)&255)<<8|e[n+2>>>2]>>>24-8*((n+2)%4)&255,s=0;4>s&&r>n+.75*s;s++)t.push(i.charAt(o>>>6*(3-s)&63));if(e=i.charAt(64))for(;t.length%4;)t.push(e);return t.join("")},parse:function(t){var t=t.replace(/\s/g,""),r=t.length,i=this._map,n=i.charAt(64);n&&(n=t.indexOf(n),-1!=n&&(r=n));
for(var n=[],o=0,s=0;r>s;s++)if(s%4){var c=i.indexOf(t.charAt(s-1))<<2*(s%4),a=i.indexOf(t.charAt(s))>>>6-2*(s%4);n[o>>>2]|=(c|a)<<24-8*(o%4),o++}return e.create(n,o)},_map:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}}(),function(t){function e(t,e,r,i,n,o,s){return t=t+(e&r|~e&i)+n+s,(t<<o|t>>>32-o)+e}function r(t,e,r,i,n,o,s){return t=t+(e&i|r&~i)+n+s,(t<<o|t>>>32-o)+e}function i(t,e,r,i,n,o,s){return t=t+(e^r^i)+n+s,(t<<o|t>>>32-o)+e}function n(t,e,r,i,n,o,s){return t=t+
(r^(e|~i))+n+s,(t<<o|t>>>32-o)+e}var o=CryptoJS,s=o.lib,c=s.WordArray,s=s.Hasher,a=o.algo,f=[];!function(){for(var e=0;64>e;e++)f[e]=4294967296*t.abs(t.sin(e+1))|0}(),a=a.MD5=s.extend({_doReset:function(){this._hash=c.create([1732584193,4023233417,2562383102,271733878])},_doProcessBlock:function(t,o){for(var s=0;16>s;s++){var c=o+s,a=t[c];t[c]=16711935&(a<<8|a>>>24)|4278255360&(a<<24|a>>>8)}for(var c=this._hash.words,a=c[0],h=c[1],u=c[2],p=c[3],s=0;64>s;s+=4)16>s?(a=e(a,h,u,p,t[o+s],7,f[s]),p=e(p,
a,h,u,t[o+s+1],12,f[s+1]),u=e(u,p,a,h,t[o+s+2],17,f[s+2]),h=e(h,u,p,a,t[o+s+3],22,f[s+3])):32>s?(a=r(a,h,u,p,t[o+(s+1)%16],5,f[s]),p=r(p,a,h,u,t[o+(s+6)%16],9,f[s+1]),u=r(u,p,a,h,t[o+(s+11)%16],14,f[s+2]),h=r(h,u,p,a,t[o+s%16],20,f[s+3])):48>s?(a=i(a,h,u,p,t[o+(3*s+5)%16],4,f[s]),p=i(p,a,h,u,t[o+(3*s+8)%16],11,f[s+1]),u=i(u,p,a,h,t[o+(3*s+11)%16],16,f[s+2]),h=i(h,u,p,a,t[o+(3*s+14)%16],23,f[s+3])):(a=n(a,h,u,p,t[o+3*s%16],6,f[s]),p=n(p,a,h,u,t[o+(3*s+7)%16],10,f[s+1]),u=n(u,p,a,h,t[o+(3*s+14)%16],
15,f[s+2]),h=n(h,u,p,a,t[o+(3*s+5)%16],21,f[s+3]));c[0]=c[0]+a|0,c[1]=c[1]+h|0,c[2]=c[2]+u|0,c[3]=c[3]+p|0},_doFinalize:function(){var t=this._data,e=t.words,r=8*this._nDataBytes,i=8*t.sigBytes;for(e[i>>>5]|=128<<24-i%32,e[(i+64>>>9<<4)+14]=16711935&(r<<8|r>>>24)|4278255360&(r<<24|r>>>8),t.sigBytes=4*(e.length+1),this._process(),t=this._hash.words,e=0;4>e;e++)r=t[e],t[e]=16711935&(r<<8|r>>>24)|4278255360&(r<<24|r>>>8)}}),o.MD5=s._createHelper(a),o.HmacMD5=s._createHmacHelper(a)}(Math),function(){var t=
CryptoJS,e=t.lib,r=e.Base,i=e.WordArray,e=t.algo,n=e.EvpKDF=r.extend({cfg:r.extend({keySize:4,hasher:e.MD5,iterations:1}),init:function(t){this.cfg=this.cfg.extend(t)},compute:function(t,e){for(var r=this.cfg,n=r.hasher.create(),o=i.create(),s=o.words,c=r.keySize,r=r.iterations;s.length<c;){a&&n.update(a);var a=n.update(t).finalize(e);n.reset();for(var f=1;r>f;f++)a=n.finalize(a),n.reset();o.concat(a)}return o.sigBytes=4*c,o}});t.EvpKDF=function(t,e,r){return n.create(r).compute(t,e)}}(),CryptoJS.lib.Cipher||
function(t){var e=CryptoJS,r=e.lib,i=r.Base,n=r.WordArray,o=r.BufferedBlockAlgorithm,s=e.enc.Base64,c=e.algo.EvpKDF,a=r.Cipher=o.extend({cfg:i.extend(),createEncryptor:function(t,e){return this.create(this._ENC_XFORM_MODE,t,e)},createDecryptor:function(t,e){return this.create(this._DEC_XFORM_MODE,t,e)},init:function(t,e,r){this.cfg=this.cfg.extend(r),this._xformMode=t,this._key=e,this.reset()},reset:function(){o.reset.call(this),this._doReset()},process:function(t){return this._append(t),this._process()},
finalize:function(t){return t&&this._append(t),this._doFinalize()},keySize:4,ivSize:4,_ENC_XFORM_MODE:1,_DEC_XFORM_MODE:2,_createHelper:function(){return function(t){return{encrypt:function(e,r,i){return("string"==typeof r?l:d).encrypt(t,e,r,i)},decrypt:function(e,r,i){return("string"==typeof r?l:d).decrypt(t,e,r,i)}}}}()});r.StreamCipher=a.extend({_doFinalize:function(){return this._process(!0)},blockSize:1});var f=e.mode={},h=r.BlockCipherMode=i.extend({createEncryptor:function(t,e){return this.Encryptor.create(t,
e)},createDecryptor:function(t,e){return this.Decryptor.create(t,e)},init:function(t,e){this._cipher=t,this._iv=e}}),f=f.CBC=function(){function e(e,r,i){var n=this._iv;n?this._iv=t:n=this._prevBlock;for(var o=0;i>o;o++)e[r+o]^=n[o]}var r=h.extend();return r.Encryptor=r.extend({processBlock:function(t,r){var i=this._cipher,n=i.blockSize;e.call(this,t,r,n),i.encryptBlock(t,r),this._prevBlock=t.slice(r,r+n)}}),r.Decryptor=r.extend({processBlock:function(t,r){var i=this._cipher,n=i.blockSize,o=t.slice(r,
r+n);i.decryptBlock(t,r),e.call(this,t,r,n),this._prevBlock=o}}),r}(),u=(e.pad={}).Pkcs7={pad:function(t,e){for(var r=4*e,r=r-t.sigBytes%r,i=r<<24|r<<16|r<<8|r,o=[],s=0;r>s;s+=4)o.push(i);r=n.create(o,r),t.concat(r)},unpad:function(t){t.sigBytes-=255&t.words[t.sigBytes-1>>>2]}};r.BlockCipher=a.extend({cfg:a.cfg.extend({mode:f,padding:u}),reset:function(){a.reset.call(this);var t=this.cfg,e=t.iv,t=t.mode;if(this._xformMode==this._ENC_XFORM_MODE)var r=t.createEncryptor;else r=t.createDecryptor,this._minBufferSize=
1;this._mode=r.call(t,this,e&&e.words)},_doProcessBlock:function(t,e){this._mode.processBlock(t,e)},_doFinalize:function(){var t=this.cfg.padding;if(this._xformMode==this._ENC_XFORM_MODE){t.pad(this._data,this.blockSize);var e=this._process(!0)}else e=this._process(!0),t.unpad(e);return e},blockSize:4});var p=r.CipherParams=i.extend({init:function(t){this.mixIn(t)},toString:function(t){return(t||this.formatter).stringify(this)}}),f=(e.format={}).OpenSSL={stringify:function(t){var e=t.ciphertext,t=
t.salt,e=(t?n.create([1398893684,1701076831]).concat(t).concat(e):e).toString(s);return e=e.replace(/(.{64})/g,"$1\n")},parse:function(t){var t=s.parse(t),e=t.words;if(1398893684==e[0]&&1701076831==e[1]){var r=n.create(e.slice(2,4));e.splice(0,4),t.sigBytes-=16}return p.create({ciphertext:t,salt:r})}},d=r.SerializableCipher=i.extend({cfg:i.extend({format:f}),encrypt:function(t,e,r,i){var i=this.cfg.extend(i),n=t.createEncryptor(r,i),e=n.finalize(e),n=n.cfg;return p.create({ciphertext:e,key:r,iv:n.iv,
algorithm:t,mode:n.mode,padding:n.padding,blockSize:t.blockSize,formatter:i.format})},decrypt:function(t,e,r,i){return i=this.cfg.extend(i),e=this._parse(e,i.format),t.createDecryptor(r,i).finalize(e.ciphertext)},_parse:function(t,e){return"string"==typeof t?e.parse(t):t}}),e=(e.kdf={}).OpenSSL={compute:function(t,e,r,i){return i||(i=n.random(8)),t=c.create({keySize:e+r}).compute(t,i),r=n.create(t.words.slice(e),4*r),t.sigBytes=4*e,p.create({key:t,iv:r,salt:i})}},l=r.PasswordBasedCipher=d.extend({cfg:d.cfg.extend({kdf:e}),
encrypt:function(t,e,r,i){return i=this.cfg.extend(i),r=i.kdf.compute(r,t.keySize,t.ivSize),i.iv=r.iv,t=d.encrypt.call(this,t,e,r.key,i),t.mixIn(r),t},decrypt:function(t,e,r,i){return i=this.cfg.extend(i),e=this._parse(e,i.format),r=i.kdf.compute(r,t.keySize,t.ivSize,e.salt),i.iv=r.iv,d.decrypt.call(this,t,e,r.key,i)}})}(),function(){var t=CryptoJS,e=t.lib.BlockCipher,r=t.algo,i=[],n=[],o=[],s=[],c=[],a=[],f=[],h=[],u=[],p=[];!function(){for(var t=[],e=0;256>e;e++)t[e]=128>e?e<<1:e<<1^283;for(var r=
0,d=0,e=0;256>e;e++){var l=d^d<<1^d<<2^d<<3^d<<4,l=l>>>8^255&l^99;i[r]=l,n[l]=r;var y=t[r],_=t[y],v=t[_],g=257*t[l]^16843008*l;o[r]=g<<24|g>>>8,s[r]=g<<16|g>>>16,c[r]=g<<8|g>>>24,a[r]=g,g=16843009*v^65537*_^257*y^16843008*r,f[l]=g<<24|g>>>8,h[l]=g<<16|g>>>16,u[l]=g<<8|g>>>24,p[l]=g,r?(r=y^t[t[t[v^y]]],d^=t[t[d]]):r=d=1}}();var d=[0,1,2,4,8,16,32,64,128,27,54],r=r.AES=e.extend({_doReset:function(){for(var t=this._key,e=t.words,r=t.sigBytes/4,t=4*((this._nRounds=r+6)+1),n=this._keySchedule=[],o=0;t>
o;o++)if(r>o)n[o]=e[o];else{var s=n[o-1];o%r?r>6&&4==o%r&&(s=i[s>>>24]<<24|i[s>>>16&255]<<16|i[s>>>8&255]<<8|i[255&s]):(s=s<<8|s>>>24,s=i[s>>>24]<<24|i[s>>>16&255]<<16|i[s>>>8&255]<<8|i[255&s],s^=d[o/r|0]<<24),n[o]=n[o-r]^s}for(e=this._invKeySchedule=[],r=0;t>r;r++)o=t-r,s=r%4?n[o]:n[o-4],e[r]=4>r||4>=o?s:f[i[s>>>24]]^h[i[s>>>16&255]]^u[i[s>>>8&255]]^p[i[255&s]]},encryptBlock:function(t,e){this._doCryptBlock(t,e,this._keySchedule,o,s,c,a,i)},decryptBlock:function(t,e){var r=t[e+1];t[e+1]=t[e+3],t[e+
3]=r,this._doCryptBlock(t,e,this._invKeySchedule,f,h,u,p,n),r=t[e+1],t[e+1]=t[e+3],t[e+3]=r},_doCryptBlock:function(t,e,r,i,n,o,s,c){for(var a=this._nRounds,f=t[e]^r[0],h=t[e+1]^r[1],u=t[e+2]^r[2],p=t[e+3]^r[3],d=4,l=1;a>l;l++)var y=i[f>>>24]^n[h>>>16&255]^o[u>>>8&255]^s[255&p]^r[d++],_=i[h>>>24]^n[u>>>16&255]^o[p>>>8&255]^s[255&f]^r[d++],v=i[u>>>24]^n[p>>>16&255]^o[f>>>8&255]^s[255&h]^r[d++],p=i[p>>>24]^n[f>>>16&255]^o[h>>>8&255]^s[255&u]^r[d++],f=y,h=_,u=v;y=(c[f>>>24]<<24|c[h>>>16&255]<<16|c[u>>>
8&255]<<8|c[255&p])^r[d++],_=(c[h>>>24]<<24|c[u>>>16&255]<<16|c[p>>>8&255]<<8|c[255&f])^r[d++],v=(c[u>>>24]<<24|c[p>>>16&255]<<16|c[f>>>8&255]<<8|c[255&h])^r[d++],p=(c[p>>>24]<<24|c[f>>>16&255]<<16|c[h>>>8&255]<<8|c[255&u])^r[d++],t[e]=y,t[e+1]=_,t[e+2]=v,t[e+3]=p},keySize:8});t.AES=e._createHelper(r)}();
function selectList(t,a,e){$(a).html(""),$(a).append("<option value=''>선택하세요</option>"),$(t).each(function(c){if("resource"==e||"groupCode"==e||"solutionFilter"==e||"solutionItem"==e)$(a).append("<option value="+t[c].value+">"+t[c].title+"</option>");else if("api"==e){var o=t[c].modelCode;$(a).append("<option value="+o+">"+o+"</option>")}else("sido"==e||"gugun"==e)&&$(a).append("<option value="+t[c]+">"+t[c]+"</option>")}),("resource"==e||"api"==e)&&$(a).append("<option value=noselect>선택사항 없음</option>")}
function consultingSubmit(){var t="",a="",e=0,c=0;$("#pdList > tr").each(function(){var a=0;$(this).find("td").each(function(){if(e>0&&0==a&&(t+=","),4>a){var c=$(this).attr("code");"noselect"==c&&(c=""),t+=c,t+="|"}4==a&&(t+=$(this).text()),a++}),e++}),$("#solutionList > tr").each(function(){var t=0;$(this).find("td").each(function(){c>0&&0==t&&(a+=","),2>t&&(a+=$(this).attr("code")),0==t&&(a+="|"),t++}),c++});var o=$("#secdevdomain").val()+"/Member/ApiLogin.aspx",n={},i=$("#secKey").val(),s=$("#secIv").val();
n.t="SC",n.name=toEncrypt($("#contactName").val(),i,s),n.email="etc"===$("#contactDomain").val()?toEncrypt($("#contactWriteEmail").val()+"@"+$("#contactWriteDomain").val(),i,s):toEncrypt($("#contactMail").val()+"@"+$("#contactDomain").val(),i,s),n.comNo=toEncrypt($("#contactComNum").val(),i,s),n.comName=toEncrypt($("#contactComName").val(),i,s),n.comTelNo=toEncrypt($("#contactPhone").val()+$("#contactPhone1").val()+$("#contactPhone2").val(),i,s),n.pdCate=t,n.solCate=a,n.HopeSido=encodeURIComponent($("#contactDdlSido option:selected").val()),
n.HopeGugun=encodeURIComponent($("#contactDdlGugun option:selected").val()),n.contents=encodeURIComponent($("#contactContent").val()),n.webPathCode=$("input:radio[name=contactRa]:checked").val(),n.webPathEtc=encodeURIComponent($("#contactTxtPath").val()),n.aKey=i,n.aIv=s,n.token=$("#sec-contact-us-token").val(),$.ajax({url:o,type:"post",data:n,xhrFields:{withCredentials:!0},dataType:"json",success:function(t){if("Y"==t.Flag)if(networkErrorCnt=0,"etc"===$("#contactDomain").val()?($("#letterDomain").val("etc").trigger("change"),
$("#letterWriteEmail").val($("#contactWriteEmail").val()),$("#letterWriteDomain").val($("#contactWriteDomain").val())):($("#letterMail").val($("#contactMail").val()),$("#letterDomain").val($("#contactDomain").val())),"Y"==letterEmailCheck()){var a=$("#pop_layer_com"),e=a.find(".btn_confirm"),c=a.find(".btn_cancel");a.show(),e.click(function(){$(".contact-tab li").eq(1).find("button").trigger("click").focus(),$("#letterName").val($("#contactName").val()),$("#letterComName").val($("#contactName").val()),
$("#letterComNum").val($("#contactComNum").val()),$("#letterPhone").val($("#contactPhone").val()),$("#letterPhone1").val($("#contactPhone1").val()),$("#letterPhone2").val($("#contactPhone2").val()),a.hide(),$(".contact-layer form").each(function(){"contact"==this.name&&this.reset()}),$("#contactWriteEmail").closest(".writeEmail").hide().find("input").val(""),$("#contactMail").prop("disabled",!1),$("#contactDomain").val(""),addListRemove()}),c.click(function(){a.hide(),contactClose()})}else closeAlert("<p>작성하신 내용으로 견적서 신청이 완료 되었습니다.</p>");
else networkError("contact")},error:function(){networkError("contact")}})}function getKeyIv(){var t=$("#secapidomain").val()+"/api/";$.ajax({type:"POST",url:t,data:{t:"GA",token:$("#sec-contact-us-token").val()},dataType:"json",cache:!1,async:!1,contentType:"application/x-www-form-urlencoded; charset=UTF-8",success:function(t){"Y"==t.Flag&&($("#secKey").val(t.data[0].Key.split("[]")[0]),$("#secIv").val(t.data[0].Iv.split("[]")[0]))}})}
function consultingCall(){$.ajax({url:"/aemapi/business/sec/admin/groupcode",type:"GET",data:{siteCode:"sec"},dataType:"json",async:!1,success:function(t){selectList(t,"#contactDdlDiv","groupCode")}}),$.ajax({url:"/aemapi/business/sec/solutionfilter",type:"GET",data:{siteCode:"sec"},dataType:"json",success:function(t){selectList(t,"#contactSolDiv","solutionFilter")}});var t=$("#secapidomain").val()+"/api/",a={};a.t="GD",a.token=$("#sec-contact-us-token").val(),a.sido="",$.ajax({url:t,type:"post",
data:a,dataType:"json",async:!1,success:function(t){for(var a=new Array,e=0;e<t.data.length;e++)a[e]=decodeURIComponent(t.data[e].sido);selectList(a,"#contactDdlSido","sido")}})}
!function(t,a){var e=a("#searchdomain").val();a("#contactDdlDiv").change(function(){var t=a("#contactDdlDiv").attr("data-select"),e=a(this).val();a(this).attr("data-select",e),(""==e||"noselect"==e||t!=e)&&(selectList("","#contactDdlDiv2","resource"),selectList("","#contactDdlDiv3","resource")),a.ajax({url:"/aemapi/business/sec/admin/typecode",type:"GET",data:{siteCode:"sec",groupCode:e},dataType:"json",success:function(t){selectList(t,"#contactDdlDiv1","resource")}})}),a("#contactDdlDiv1").change(function(){var t=
a("#contactDdlDiv1").attr("data-select"),e=a("#contactDdlDiv").attr("data-select"),c=a(this).val();a(this).attr("data-select",c),(""==c||"noselect"==c||c!=t)&&selectList("","#contactDdlDiv3","resource"),a.ajax({url:"/aemapi/business/sec/admin/subtypecode",type:"GET",data:{siteCode:"sec",groupCode:e,typeCode:c},dataType:"json",success:function(t){selectList(t,"#contactDdlDiv2","resource")}})}),a("#contactDdlDiv2").change(function(){var t=a("#contactDdlDiv1").attr("data-select"),c=a(this).val();a(this).attr("data-select",
c),a.ajax({url:e+"/business/modelList",type:"GET",data:{siteCd:"sec",stage:"qa",typeIA:t,subTypeIA:c},dataType:"json",success:function(t){t=t.response.resultData.resultList;for(var a,e=0;e<t.length;e++)t[e].subTypeIA==c&&(a=t[e].modelList);selectList(a,"#contactDdlDiv3","api")}})}),a("#contactDdlDiv3").change(function(){var t=a(this).val();a(this).attr("data-select",t)}),a("#contactSolDiv").change(function(){var t=a(this).val();a(this).attr("data-select",t),a.ajax({url:"/aemapi/business/sec/solutionitem",
type:"GET",data:{siteCode:"sec",solutionFilter:t},dataType:"json",success:function(t){selectList(t,"#contactSolDiv1","solutionItem")}})}),a("#contactSolDiv1").change(function(){var t=a(this).val();a(this).attr("data-select",t)}),a("#contactDdlSido").change(function(){var t=a(this).val();a(this).attr("data-select",t);var e=a("#secapidomain").val()+"/api/",c={};c.t="GD",c.token=a("#sec-contact-us-token").val(),c.sido=t,a.ajax({url:e,type:"post",data:c,dataType:"json",async:!1,success:function(t){for(var a=
new Array,e=0;e<t.data.length;e++)a[e]=decodeURIComponent(t.data[e].gugun);selectList(a,"#contactDdlGugun","gugun")}})})}(window,window.jQueryOld);function toEncrypt(t,e,a){var n=CryptoJS.AES.encrypt(CryptoJS.enc.Utf8.parse(t),CryptoJS.enc.Utf8.parse(e),{keySize:16,iv:CryptoJS.enc.Utf8.parse(a),mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7}).toString();return n}
function toDecrypt(t,e,a){var n=CryptoJS.AES.decrypt(t,CryptoJS.enc.Utf8.parse(e),{keySize:16,iv:CryptoJS.enc.Utf8.parse(a),mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7}).toString(CryptoJS.enc.Utf8);return n}
!function(t,e){function a(t){e("#sec-contact-audiocatpch").html(' <bgsound src="'+t+'">')}function n(){var t=new Date,e="http://"+window.location.host+"/aemapi/business/common/simpleaudiocapcha.SEC-CON.Y?"+t.getTime(),n=navigator.userAgent.toLowerCase();if("Netscape"==navigator.appName&&n.indexOf("trident")>=0){var o='<object type="audio/x-wav" data="'+e+'" width="0" height="0"><param name="src" value="'+e+'"/><param name="autostart" value="true" /><param name="controller" value="false" /></object>';
document.getElementById("sec-contact-audiocatpch").innerHTML=o}else if(n.indexOf("msie")>=0)a(e+"&agent=msie");else try{var c=new Audio(e);c.load(),c.play()}catch(r){a(e)}}function o(){var t=new Date;e(".contact-layer .capcha-image img").attr("src","https://"+window.location.host+"/aemapi/business/common/simplecapcha.SEC-CON.Y?"+t.getTime())}e(".contact-layer button.btn-audio").unbind("click").click(function(){n()}),e(".contact-layer button.btn-refresh").unbind("click").click(function(){o()})}(window,
window.jQueryOld);
function letterChk(e){var t=$('[name="letterMail"]'),a=$('[name="letterDomain"]'),l=$('[name="letterWriteEmail"]'),r=$('[name="letterWriteDomain"]'),n="",o="";if("etc"!==a.val()||l.val())if("etc"!==a.val()||r.val())if("etc"===a.val()||t.val())if("etc"===a.val()||a.val()){var c=letterEmailCheck();"N"==c?(o="<p>기존 뉴스레터 수신 동의자 입니다.</p>",alertCom(e,o)):"Y"==c?(o="<p>뉴스레터 신청이 가능합니다.</p>",alertCom(e,o)):(setSecToken(),alertCom($(".contact-contents"),"<p>잠시 후 다시 시도해 주세요.</p>"))}else o="<p>고객님의 이메일 도메인을 선택해 주시기 바랍니다.</p>",
n=a,alertCom(n,o);else o="<p>고객님의 이메일 계정을 입력해 주시기 바랍니다.</p>",n=t,alertCom(n,o);else o="<p>고객님의 이메일 도메인을 입력해 주시기 바랍니다.</p>",n=r,alertCom(n,o);else o="<p>고객님의 이메일계정을 입력해 주시기 바랍니다.</p>",n=l,alertCom(n,o)}
function letterEmailCheck(){var e=$('[name="letterMail"]'),t=$('[name="letterDomain"]'),a=$('[name="letterWriteEmail"]'),l=$('[name="letterWriteDomain"]'),r=$("#secKey").val(),n=$("#secIv").val(),o=$("#secapidomain").val()+"/api/",c="",i="E",m={};return c="etc"===t.val()?a.val()+"@"+l.val():e.val()+"@"+t.val(),m.t="GN",m.Email=toEncrypt(c,r,n),m.aKey=r,m.aIv=n,m.token=$("#sec-contact-us-token").val(),$.ajax({url:o,type:"post",data:m,dataType:"json",async:!1,success:function(e){"Y"==e.Flag?i="Y":"already"==
e.data[0].Msg&&(i="N")}}),i}
function letterSubmit(){var e=$("#secdevdomain").val()+"/Member/ApiLogin.aspx",t={},a=$("#secKey").val(),l=$("#secIv").val();t.t="SN",t.name=toEncrypt($("#letterName").val(),a,l),t.email="etc"===$("#letterDomain").val()?toEncrypt($("#letterWriteEmail").val()+"@"+$("#letterWriteDomain").val(),a,l):toEncrypt($("#letterMail").val()+"@"+$("#letterDomain").val(),a,l),t.comNo=toEncrypt($("#letterComNum").val(),a,l),t.comName=toEncrypt($("#letterComName").val(),a,l),t.comTelNo=toEncrypt($("#letterPhone").val()+
$("#letterPhone1").val()+$("#letterPhone2").val(),a,l),t.idNo=$("[name=letterRa]:checked").val(),t.aKey=a,t.aIv=l,t.token=$("#sec-contact-us-token").val(),$.ajax({url:e,type:"post",data:t,xhrFields:{withCredentials:!0},dataType:"json",success:function(e){"Y"==e.Flag?(networkErrorCnt=0,closeAlert("<p>뉴스레터 신청이 완료 되었습니다.</p>"),$("form").each(function(){"letter"==this.name&&this.reset()})):networkError("letter")},error:function(){networkError("letter")}})}
function qnaSubmit(){var a=$("#secdevdomain").val()+"/Member/ApiLogin.aspx",e={},n=$("#secKey").val(),t=$("#secIv").val();e.t="SQ",e.name=toEncrypt($("#qnaName").val(),n,t),e.email="etc"===$("#qnaDomain").val()?toEncrypt($("#qnaWriteEmail").val()+"@"+$("#qnaWriteDomain").val(),n,t):toEncrypt($("#qnaEmail").val()+"@"+$("#qnaDomain").val(),n,t),e.comTelno=toEncrypt($("#qnaPhone").val()+$("#qnaPhone1").val()+$("#qnaPhone2").val(),n,t),e.qnaType=$("#qnaDivSort").val(),e.Title=encodeURIComponent($("#qnaSubject").val()),
e.partnerType=$("#qnaPartnerType").val(),e.officeSize=$("#qnaOfficeSize").val(),e.webPathCode=$("[name=rdoPath]:checked").val(),"WPT00"===e.webPathCode&&(e.webPathEtc=encodeURIComponent($("#qnaTxtPath").val())),e.Contents=encodeURIComponent($("#qnaContent").val()),e.aKey=n,e.aIv=t,e.token=$("#sec-contact-us-token").val(),$.ajax({url:a,type:"post",data:e,xhrFields:{withCredentials:!0},dataType:"json",success:function(a){"Y"==a.Flag?(networkErrorCnt=0,closeAlert("<p>고객문의 신청이 완료 되었습니다.</p>"),$("form").each(function(){"qna"==
this.name&&this.reset()})):networkError("qna")},error:function(){networkError("qna")}})}!function(a,e){e("#partnerArea1").hide(),e("#partnerArea2").hide()}(window,window.jQueryOld);
function contactOpen(t,e,a,n,o){var c=$("#searchdomain").val();$(".contact-layer").show().find(".contact-tab li").eq(t).find("button").trigger("click").focus(),void 0!=e&&(productInfo(e,"#contactDdlDiv"),$.ajax({url:"/aemapi/business/sec/admin/typecode",type:"GET",data:{siteCode:"sec",groupCode:e},dataType:"json",async:!1,success:function(t){selectList(t,"#contactDdlDiv1","resource")}})),void 0!=a&&(productInfo(a,"#contactDdlDiv1"),$.ajax({url:"/aemapi/business/sec/admin/subtypecode",type:"GET",data:{siteCode:"sec",
groupCode:e,typeCode:a},dataType:"json",async:!1,success:function(t){selectList(t,"#contactDdlDiv2","resource")}})),void 0!=n&&(productInfo(n,"#contactDdlDiv2"),$.ajax({url:c+"/business/modelList",type:"GET",data:{siteCd:"sec",stage:"qa",typeIA:a,subTypeIA:n},dataType:"json",async:!1,success:function(t){t=t.response.resultData.resultList;for(var e,a=0;a<t.length;a++)t[a].subTypeIA==n&&(e=t[a].modelList);selectList(e,"#contactDdlDiv3","api")}})),void 0!=o&&productInfo(o,"#contactDdlDiv3")}
function productInfo(t,e){$(e).find("option").each(function(){t==$(this).val()&&($(this).attr("selected","selected"),$(e).attr("data-select",t))})}
function contactClose(){$(".contact-layer").hide(),$(".contact-layer form").each(function(){("letter"==this.name||"contact"==this.name||"qna"==this.name)&&this.reset()}),$(".writeEmail").hide().find("input").val(""),$("#contactMail, #letterMail, #qnaEmail").prop("disabled",!1),$("#contactDomain, #letterDomain, #qnaDomain").val(""),$("#partnerArea1").hide(),$("#partnerArea2").hide(),addListRemove(),$("#bu-g-gnb_01_1400101").trigger("focus")}
function setSecToken(){$.ajax({url:"/sysapi/business/sec/token",type:"GET",dataType:"json",async:!1,success:function(t){$("#sec-contact-us-token").val(t.response.token),getKeyIv()}})}
function tabMenu(t){var e,a=t.parent().parent().index(),n=$(".contact-content"),o=$("#secdevdomain").val()+"/Member/ApiLogin.aspx";t.parent().parent().addClass("active").siblings().removeClass("active"),n.hide().eq(a).show(),$(".contact-layer .btn-refresh").trigger("click"),setSecToken(),e=$("#sec-contact-us-token").val(),0==a?(consultingCall(),$.ajax({url:o,type:"post",data:{token:e,t:"LC"},xhrFields:{withCredentials:!0},async:!1,dataType:"json",success:function(t){var e=$("#contact");if(e.find(".txt_clause:eq(0)").html(t.data[0].Agree1),
e.find(".txt_clause:eq(1)").html(t.data[0].Agree2),"N"!=t.Flag){var a=t.data[0].aKey,n=t.data[0].aIv,o=toDecrypt(t.data[0].Name,a,n),c=toDecrypt(t.data[0].Email,a,n),l=toDecrypt(t.data[0].Telno,a,n),i=toDecrypt(t.data[0].comNo,a,n),r=toDecrypt(t.data[0].comName,a,n),s=c.split("@")[1],p=3,d=0,m=11;c=c.split("@")[0],l.length<11&&"02"==l.substr(0,2)&&(p--,m--),d=l.length<m?3:4,$("#contactName").val(o),$("#contactDomain").find("[value='"+s+"']").length>0?($("#contactMail").val(c),$("#contactDomain").val(s)):
($("#contactDomain").val("etc").trigger("change"),$("#contactWriteEmail").val(c),$("#contactWriteDomain").val(s)),$("#contactComName").val(r),$("#contactComNum").val(i),$("#contactPhone").val(l.substr(0,p)),$("#contactPhone1").val(l.substr(p,d)),$("#contactPhone2").val(l.substr(p+d,4))}},error:function(){closeAlert("<p>잠시 후 다시 시도해주세요.</p>")}})):1==a?$.ajax({url:o,type:"post",data:{token:e,t:"LN"},dataType:"json",xhrFields:{withCredentials:!0},async:!1,success:function(t){if("Y"==t.Flag){var e=$("#letterForm");
e.find(".txt_clause").html(t.data[0].Agree1)}else closeAlert("already"==t.data[0].Msg?"<p>기존 뉴스레터 수신 동의자 입니다.</p>":"<p>잠시 후 다시 시도해주세요.</p>")},error:function(){closeAlert("<p>잠시 후 다시 시도해주세요.</p>")}}):2==a&&$.ajax({url:o,type:"post",data:{token:e,t:"LQ"},xhrFields:{withCredentials:!0},dataType:"json",async:!1,success:function(t){var e=$("#qnaForm");if(e.find(".txt_clause:eq(0)").html(t.data[0].Agree1),e.find(".txt_clause:eq(1)").html(t.data[0].Agree2),"N"!=t.Flag){var a=t.data[0].aKey,n=t.data[0].aIv,
o=toDecrypt(t.data[0].Email,a,n),c=toDecrypt(t.data[0].Telno,a,n),l=o.split("@")[1],i=0,r=3,s=11;o=o.split("@")[0],c.length<11&&"02"==c.substr(0,2)&&(r--,s--),i=c.length<s?3:4,$("#qnaName").val(toDecrypt(t.data[0].Name,a,n)),$("#qnaDomain").find("[value='"+l+"']").length>0?($("#qnaEmail").val(o),$("#qnaDomain").val(l)):($("#qnaDomain").val("etc").trigger("change"),$("#qnaWriteEmail").val(o),$("#qnaWriteDomain").val(l)),$("#qnaPhone").val(c.substr(0,r)),$("#qnaPhone1").val(c.substr(r,i)),$("#qnaPhone2").val(c.substr(r+
i,4))}},error:function(){closeAlert("<p>잠시 후 다시 시도해주세요.</p>")}})}function layerOpen(t){$(t).show()}function layerClose(t){t.closest(".pop_layer").hide(),$(".contact-layer").removeClass("comSearchOn"),$(".opnerLayerBtn").trigger("focus"),$(".opnerLayerBtn").removeClass("opnerLayerBtn")}
function comSrhOpen(t){$(".contact-layer").addClass("comSearchOn"),$(".pop_layer").hide(),$(t).find("input").val(""),$("#companyList").empty(),$("#chbExSearch").prop("checked",!1),$(t).show();var e=$(event.srcElement||event.target);e.addClass("opnerLayerBtn"),$(t).attr("tabindex",0).trigger("focus")}
function addListRemove(){$(".pdAddList, .solAddList").closest(".td").removeClass("on"),$(".pdAddList, .solAddList").find(".multiple_list button").remove(),$(".pdAddTableList .addList, .solAddTableList .addList").find("tr").remove()}
function addList(t,e){var a,n,o,c,l,i,r,s,p,d=t.closest(".td"),m="",u="",v=d.find(".multiple_list"),h="",f="",C="",g="";if("pd"===e){if(a=$('[name="contactDdlDiv"]'),n=$('[name="contactDdlDiv1"] option:selected'),o=$('[name="contactDdlDiv2"] option:selected'),c=$('[name="contactDdlDiv3"] option:selected'),s=$("#contactCnt"),m=d.find(".pdAddTableList .addList"),""===a.val())return alertCom(a,"<p>제품군을 선택해 주시기 바랍니다.</p>"),!1;if(""!==n.val()?(h+=" / "+n.text(),l=n.text()):void 0===l&&(l=""),""!==o.val()?
(h+=" / "+o.text(),i=o.text()):void 0===i&&(i=""),""!==c.val()?(h+=" / "+c.text(),r=c.text()):void 0===r&&(r=""),""===s.val())alertCom(s,"<p>수량을 입력해 주시기 바랍니다.</p>");else if(s.val().search(/^[0-9]*$/))s.select(),alertCom(s,"<p>수량은 숫자로 입력해 주시기 바랍니다.</p>");else if(!s.val().search(/^[0-9]*$/)){f='<button type="button">'+a.children("option:selected").text(),C=" : "+s.val()+"</button>",g=f+h+C;var b=$('[name="contactDdlDiv"]').attr("data-select"),D=$('[name="contactDdlDiv1"]').attr("data-select"),y=$('[name="contactDdlDiv2"]').attr("data-select"),
q=$('[name="contactDdlDiv3"]').attr("data-select");u="<tr><td code="+b+">"+a.children("option:selected").text()+"</td><td code="+D+">"+l+"</td><td code="+y+">"+i+"</td><td code="+q+">"+r+"</td><td>"+s.val()+'</td><td><button type="button" class="btnDel"><img src="sec/static/etc/designs/samsung/global/business/imgs/btn_del.gif" alt="현재 줄 제품 삭제"></button></td></tr>',d.addClass("on")}v.append(g),m.append(u)}else if("sol"===e){if(a=$('[name="contactSolDiv"]'),n=$('[name="contactSolDiv1"]'),p=$('[name="contactSolDiv1"] option:selected'),
m=d.find(".solAddTableList .addList"),f='<button type="button">'+a.children("option:selected").text(),C="</button>",""===a.val())return alertCom(a,"<p>솔루션을 선택해 주시기 바랍니다.</p>"),!1;if(""===n.val())return alertCom(n,"<p>솔루션을 선택해 주시기 바랍니다.</p>"),!1;h+=" / "+p.text(),g=f+h+C,v.append(g);var x=$('[name="contactSolDiv"]').attr("data-select"),k=$('[name="contactSolDiv1"]').attr("data-select");u="<tr><td code="+x+">"+a.children("option:selected").text()+"</td><td code="+k+">"+p.text()+'</td><td><button type="button" class="btnDel"><img src="sec/static/etc/designs/samsung/global/business/imgs/btn_del.gif" alt="현재 줄 제품 삭제"></button></td></tr>',
m.append(u),d.addClass("on")}$(".addList").off().on("click",".btnDel",function(){var t=$(this),e=t.closest("tr").index();1===t.closest(".td").find(".addList tr").length&&t.closest(".td").removeClass("on"),t.closest(".td").find(".multiple_list button").eq(e).remove(),t.closest("tr").remove();var a=$("#solutionList tr");0==a.size()?$("#contact .p5_tbl_form .p_info:eq(1) .btn-dell").trigger("focus"):0==e?a.first().find("button").trigger("focus"):e==a.size()?a.last().find("button").trigger("focus"):a.eq(e).find("button").trigger("focus")})}
function listDel(t){var e=t.closest(".td"),a=e.find(".multiple_list"),n=e.find('[class*="AddTableList"]');a.find("button.on").remove(),n.find("tr.on").remove(),setTimeout(function(){(a.find("button").length<1||n.find("tr").length<1)&&e.removeClass("on")},10)}
function alertCom(t,e,a,n){var o=$("#pop_layer_alert"),c=o.find(".pop_content"),l=o.find(".btn-back"),i=o.find(".btn-cancel");c.find("p").remove(),c.prepend(e),i.hide(),o.show(),l.off("click"),"reset"===t?(i.hide(),l.focus().click(function(){$("#"+a+"AgreeAll, #"+a+"Agree1, #"+a+"Agree2, #"+a+"Agree").prop("checked",!1),$("#"+a+"Capcha").focus().val(""),o.hide()})):n?(i.show(),l.click(function(){"https://www.samsung.com/sec/business/support/member/regular-signup/"==n?window.open(n):"https://account.samsung.com/account/check.do"==
n?goAccount():location.href=n}),i.off("click"),i.click(function(){o.hide(),t.focus()})):l.focus().click(function(){a?a.submit():(o.hide(),t.focus())})}function closeAlert(t){var e=$("#pop_layer_alert"),a=e.find(".pop_content"),n=e.find(".btn-back"),o=e.find(".btn-cancel");a.find("p").remove(),a.prepend(t),o.hide(),e.show(),n.off("click"),n.focus().click(function(){e.hide(),contactClose()})}
function networkError(t){var e="";"contact"===t?e='<p style="margin-top:-20px;">견적문의 보내기에 실패하였습니다.<br> 다시 시도하시겠습니까?</p>':"letter"===t?e='<p style="margin-top:-20px;">뉴스레터 신청 보내기에 실패하였습니다.<br> 다시 시도하시겠습니까?</p>':"qna"===t&&(e='<p style="margin-top:-20px;">고객문의 보내기에 실패하였습니다.<br> 다시 시도하시겠습니까?</p>'),networkErrorCnt++,networkErrorCnt>2&&(e="<p>잠시 후 다시 시도해주세요.</p>",networkErrorCnt=0),setSecToken(),alertCom("reset",e,t)}
function goAccount(){var t=$("#loginForm"),e=window.location.href;"desktop"!=ss.Detect().device?t.attr("action","https://account.samsung.com/mobile/account/check.do"):t.attr("action","https://account.samsung.com/account/check.do"),$("#returnURL",t).val(encodeURIComponent(e)),$("#goBackURL",t).val(encodeURIComponent(e));var a=$("#registURL",t).val();if("sec"!=SITE_CD){var n="",o=window.location.port;if(n=null==o||""==o||"80"==o||"8080"==o?"https://"+window.location.host:"http://"+window.location.host,
a.indexOf(window.location.hostname)<0){var c=n+a;$("#registURL",t).val(c)}}var l=$("#emailActivationURL",t).val();if(l.indexOf(window.location.hostname)<0){var i=window.location.protocol+"//"+window.location.host+l;$("#emailActivationURL",t).val(i)}t.submit()}
function comChk(t){var e,a,n,o,c,l="";$("#companyList").html(""),"srh"===t?(e=$('[name="txtPopComName"]'),a=$('[name="txtComNo1"]'),n=$('[name="txtComNo2"]'),o=$('[name="txtComNo3"]'),c=$('[name="txtComNo1"]').val()+$('[name="txtComNo2"]').val()+$('[name="txtComNo3"]').val(),0==e.val().length&&0==c.length?alertCom(e,"<p>회사명, 사업자번호중 하나를 입력한 후 검색하세요.</p>"):e.val().length>0&&e.val().length<2?alertCom(e,"<p>회사명을 2자이상 입력하세요.</p>"):c.length>1&&c.length<10||a.val().search(/^[0-9]*$/)?(l="<p>올바른 사업자 등록번호를 입력해 주세요.</p>",
a.val().length<3||a.val().search(/^[0-9]*$/)?alertCom(a,l):n.val().length<2||n.val().search(/^[0-9]*$/)?alertCom(n,l):(o.val().length<5||o.val().search(/^[0-9]*$/))&&alertCom(o,l)):companySrch()):"reg"===t&&(e=$('[name="txtDPopComName"]'),a=$('[name="txtDPopComNo1"]'),n=$('[name="txtDPopComNo2"]'),o=$('[name="txtDPopComNo3"]'),c=a.val()+n.val()+o.val(),e.val().length<2?alertCom(e,"<p>회사명을 2자이상 입력하세요.</p>"):""==a.val()||a.val().length<3||a.val().search(/^[0-9]*$/)?(""==a.val()?l="<p>사업자 등록 번호를 입력해 주시기 바랍니다.</p>":
(a.val().length<3||a.val().search(/^[0-9]*$/))&&(l="<p>올바른 사업자 등록번호를 입력해 주세요.</p>",a.select()),alertCom(a,l)):""==n.val()||n.val().length<2||n.val().search(/^[0-9]*$/)?(""==n.val()?l="<p>사업자 등록 번호를 입력해 주시기 바랍니다.</p>":(n.val().length<2||n.val().search(/^[0-9]*$/))&&(l="<p>올바른 사업자 등록번호를 입력해 주세요.</p>",n.select()),alertCom(n,l)):""==o.val()||o.val().length<5||o.val().search(/^[0-9]*$/)?(""==o.val()?l="<p>사업자 등록 번호를 입력해 주시기 바랍니다.</p>":(o.val().length<5||o.val().search(/^[0-9]*$/))&&(l="<p>올바른 사업자 등록번호를 입력해 주세요.</p>",
o.select()),alertCom(o,l)):($("#letterComName").val(e.val()),$("#contactComName").val(e.val()),$("#letterComNum").val(c),$("#contactComNum").val(c),$(".pop_layer").hide(),$(".contact-layer").removeClass("comSearchOn")))}
function companySrch(){var t=$("#secapidomain").val()+"/api/",e=$("#txtComNo1").val()+$("#txtComNo2").val()+$("#txtComNo3").val(),a=encodeURIComponent($("#txtPopComName").val()),n=$("#sec-contact-us-token").val(),o="N",c=$("#companyList");c.html(""),document.getElementById("chbExSearch").checked&&(o="Y"),$.ajax({url:t,type:"post",data:{token:n,t:"GC",excheck:o,comname:a,comno:e},dataType:"json",success:function(t){if("Y"==t.Flag){c.html("");for(var e in t.data)c.append("<tr><td><button type='button'>"+
decodeURIComponent(t.data[e].comname)+"</button></td><td>"+decodeURIComponent(t.data[e].comno).substr(0,3)+"-"+decodeURIComponent(t.data[e].comno).substr(3,2)+"-"+decodeURIComponent(t.data[e].comno).substr(5,5)+"</td></tr>");0==t.data.length&&c.html('<tr><td colspan="2"><div class="data_none"><div class="txt">데이터가 없습니다.</div><ul class="btn_wrap2"><li><button type="button" class="btn-type1 btn_company_register" onclick="comSrhOpen(pop_layer_register)">직접 회사등록</button></li></ul></div></td></tr>')}else setSecToken(),
alertCom($("#txtPopComName"),"<p>잠시 후 다시 시도해 주세요.</p>")},error:function(){setSecToken(),alertCom($("#txtPopComName"),"<p>잠시 후 다시 시도해 주세요.</p>")}})}function check_email(t){var e=/(@.*@)|(\.\.)|(@\.)|(\.@)|(^\.)/,a=/^[a-zA-Z0-9\-\._]+@[a-zA-Z0-9\-\.]+\.([a-zA-Z]{2,3})$/,n=!1;return!e.test(t)&&a.test(t)&&(n=!0),n}
function confirm(t){var e,a,n,o,c="";if("contact"===t)e=$("[name="+t+"]"),a=document.forms[t],n=e.find(".writeEmail").is(":visible")?a.contactWriteEmail.value+"@"+a.contactWriteDomain.value:a.contactMail.value+"@"+a.contactDomain.value,a.contactName.value?"etc"!==a.contactDomain.value||a.contactWriteEmail.value?"etc"!==a.contactDomain.value||a.contactWriteDomain.value?"etc"===a.contactDomain.value||a.contactMail.value?"etc"===a.contactDomain.value||a.contactDomain.value?check_email(n)?a.contactComName.value?
a.contactPhone.value.search(/^[0-9]*$/)||!a.contactPhone.value?(a.contactPhone.value?a.contactPhone.value.search(/^[0-9]*$/)&&(c="<p>연락처는 숫자로만 입력해 주시기 바랍니다.</p>",a.contactPhone.select()):c="<p>고객님의 회사연락처를 입력해 주시기 바랍니다.</p>",o=a.contactPhone,alertCom(o,c)):a.contactPhone1.value.search(/^[0-9]*$/)||!a.contactPhone1.value?(a.contactPhone1.value?a.contactPhone1.value.search(/^[0-9]*$/)&&(c="<p>연락처는 숫자로만 입력해 주시기 바랍니다.</p>",a.contactPhone1.select()):c="<p>고객님의 회사연락처를 입력해 주시기 바랍니다.</p>",o=a.contactPhone1,
alertCom(o,c)):a.contactPhone2.value.search(/^[0-9]*$/)||!a.contactPhone2.value||a.contactPhone2.value.length<4?(a.contactPhone2.value?a.contactPhone2.value.search(/^[0-9]*$/)?(c="<p>연락처는 숫자로만 입력해 주시기 바랍니다.</p>",a.contactPhone2.select()):a.contactPhone2.value.length<4&&(c="<p>올바른 연락처 형식이 아닙니다.</p>",a.contactPhone2.select()):c="<p>고객님의 회사연락처를 입력해 주시기 바랍니다.</p>",o=a.contactPhone2,alertCom(o,c)):$(".pdAddList .multiple_list button").length<1?(a.contactCnt.value?a.contactDdlDiv.value&&a.contactCnt.value?
(c="<p>[추가] 버튼을 눌러 제품군을 추가해 주세요.</p>",o=$("#contactCnt").closest(".row").find(".btn-type5")):(c="<p>제품군을 선택해 주시기 바랍니다.</p>",o=a.contactDdlDiv):(c="<p>수량 입력 후 [추가] 버튼을 눌러 제품군을 추가해 주세요.</p>",o=a.contactCnt),alertCom(o,c)):a.contactDdlSido.value?a.contactDdlGugun.value?a.contactCapcha.value?isCaptchaValidCheck(a.contactCapcha.value)?a.contactAgree1.checked?a.contactAgree2.checked?consultingSubmit():(c="<p>개인정보 제3자 제공 동의란에 체크해 주시기 바랍니다.</p>",o=a.contactAgree2,alertCom(o,c)):(c="<p>개인정보 수집/처리란에 체크해 주시기 바랍니다.</p>",
o=a.contactAgree1,alertCom(o,c)):(c="<p>보안코드가 일치하지 않습니다.</p>",o=a.contactCapcha,alertCom(o,c)):(c="<p>보안코드를 입력해 주시기 바랍니다.</p>",o=a.contactCapcha,alertCom(o,c)):(c="<p>설치현장 구/군을 선택해 주시기 바랍니다.</p>",o=a.contactDdlGugun,alertCom(o,c)):(c="<p>설치현장 시/도를 선택해 주시기 바랍니다.</p>",o=a.contactDdlSido,alertCom(o,c)):(c="<p>고객님의 회사명을 입력해 주시기 바랍니다.</p>",o=a.contactComName,alertCom(o,c)):(c="<p>올바른 이메일 형식이 아닙니다.</p>",o=$(".writeEmail").is(":visible")?a.contactWriteEmail:a.contactMail,alertCom(o,c)):(c="<p>고객님의 이메일 도메인을 선택해 주시기 바랍니다.</p>",
o=a.contactDomain,alertCom(o,c)):(c="<p>고객님의 이메일 계정을 입력해 주시기 바랍니다.</p>",o=a.contactMail,alertCom(o,c)):(c="<p>고객님의 이메일 도메인을 입력해 주시기 바랍니다.</p>",o=a.contactWriteDomain,alertCom(o,c)):(c="<p>고객님의 이메일계정을 입력해 주시기 바랍니다.</p>",o=a.contactWriteEmail,alertCom(o,c)):(c="<p>고객님의 이름을 입력해 주시기 바랍니다.</p>",o=a.contactName,alertCom(o,c));else if("letter"===t)if(e=$("[name="+t+"]"),a=document.forms[t],n=e.find(".writeEmail").is(":visible")?a.letterWriteEmail.value+"@"+a.letterWriteDomain.value:a.letterMail.value+"@"+
a.letterDomain.value,a.letterName.value)if("etc"!==a.letterDomain.value||a.letterWriteEmail.value)if("etc"!==a.letterDomain.value||a.letterWriteDomain.value)if("etc"===a.letterDomain.value||a.letterMail.value)if("etc"===a.letterDomain.value||a.letterDomain.value)if(check_email(n))if(a.letterCapcha.value)if(isCaptchaValidCheck(a.letterCapcha.value))if(a.letterAgree.checked){var l=letterEmailCheck();"N"==l?(c="<p>기존 뉴스레터 수신 동의자 입니다.</p>",alertCom($(".contact-contents"),c)):"Y"==l?letterSubmit():closeAlert("<p>잠시 후 다시 시도해 주세요.</p>")}else c=
"<p>개인정보 수집/처리란에 체크해 주시기 바랍니다.</p>",o=a.letterAgree,alertCom(o,c);else c="<p>보안코드가 일치하지 않습니다</p>",o=a.letterCapcha,alertCom(o,c);else c="<p>보안코드를 입력해 주시기 바랍니다.</p>",o=a.letterCapcha,alertCom(o,c);else c="<p>올바른 이메일 형식이 아닙니다.</p>",o=$(".writeEmail").is(":visible")?a.letterWriteEmail:a.letterMail,alertCom(o,c);else c="<p>고객님의 이메일 도메인을 선택해 주시기 바랍니다.</p>",o=a.letterDomain,alertCom(o,c);else c="<p>고객님의 이메일 계정을 입력해 주시기 바랍니다.</p>",o=a.letterMail,alertCom(o,c);else c="<p>고객님의 이메일 도메인을 입력해 주시기 바랍니다.</p>",
o=a.letterWriteDomain,alertCom(o,c);else c="<p>고객님의 이메일계정을 입력해 주시기 바랍니다.</p>",o=a.letterWriteEmail,alertCom(o,c);else c="<p>고객님의 이름을 입력해 주시기 바랍니다.</p>",o=a.letterName,alertCom(o,c);else"qna"===t&&(e=$("[name="+t+"]"),a=document.forms[t],n=e.find(".writeEmail").is(":visible")?a.qnaWriteEmail.value+"@"+a.qnaWriteDomain.value:a.qnaEmail.value+"@"+a.qnaDomain.value,a.qnaName.value?"etc"!==a.qnaDomain.value||a.qnaWriteEmail.value?"etc"!==a.qnaDomain.value||a.qnaWriteDomain.value?"etc"===a.qnaDomain.value||
a.qnaEmail.value?"etc"===a.qnaDomain.value||a.qnaDomain.value?check_email(n)?a.qnaPhone.value.search(/^[0-9]*$/)||!a.qnaPhone.value?(a.qnaPhone.value?a.qnaPhone.value.search(/^[0-9]*$/)&&(c="<p>연락처는 숫자로만 입력해 주시기 바랍니다.</p>",a.qnaPhone.select()):c="<p>고객님의 회사연락처를 입력해 주시기 바랍니다.</p>",o=a.qnaPhone,alertCom(o,c)):a.qnaPhone1.value.search(/^[0-9]*$/)||!a.qnaPhone1.value?(a.qnaPhone1.value?a.qnaPhone1.value.search(/^[0-9]*$/)&&(c="<p>연락처는 숫자로만 입력해 주시기 바랍니다.</p>",a.qnaPhone1.select()):c="<p>고객님의 회사연락처를 입력해 주시기 바랍니다.</p>",
o=a.qnaPhone1,alertCom(o,c)):a.qnaPhone2.value.search(/^[0-9]*$/)||!a.qnaPhone2.value||a.qnaPhone2.value.length<4?(a.qnaPhone2.value?a.qnaPhone2.value.length<4?(c="<p>올바른 연락처 형식이 아닙니다.</p>",a.qnaPhone2.select()):a.qnaPhone2.value.search(/^[0-9]*$/)&&(c="<p>연락처는 숫자로만 입력해 주시기 바랍니다.</p>",a.qnaPhone2.select()):c="<p>고객님의 회사연락처를 입력해 주시기 바랍니다.</p>",o=a.qnaPhone2,alertCom(o,c)):a.qnaDivSort.value?"QNA22"!=$("#qnaDivSort").val()||!a.qnaOfficeSize.value.search(/^[0-9]*$/)&&a.qnaOfficeSize.value?"QNA22"!=$("#qnaDivSort").val()||
a.qnaPartnerType.value?a.qnaSubject.value?a.qnaContent.value&&""!=a.qnaContent.value.replace(/^\s+|\s+$/g,"")?a.qnaCapcha.value?isCaptchaValidCheck(a.qnaCapcha.value)?a.qnaAgree.checked?a.qnaAgree1.checked?qnaSubmit():(c="<p>개인정보 위탁 동의란에 체크해 주시기 바랍니다.</p>",o=a.qnaAgree1,alertCom(o,c)):(c="<p>개인정보 수집/처리 동의란에 체크해 주시기 바랍니다.</p>",o=a.qnaAgree,alertCom(o,c)):(c="<p>보안코드가 일치하지 않습니다</p>",o=a.qnaCapcha,alertCom(o,c)):(c="<p>보안코드를 입력해 주시기 바랍니다.</p>",o=a.qnaCapcha,alertCom(o,c)):(c="<p>문의 내용을 입력해 주시기 바랍니다.</p>",
o=a.qnaContent,alertCom(o,c)):(c="<p>문의 제목을 입력해 주시기 바랍니다.</p>",o=a.qnaSubject,alertCom(o,c)):(c="<p>희망 파트너(판매점) 유형을 선택해 주시기 바랍니다.</p>",o=a.qnaPartnerType,alertCom(o,c)):(a.qnaOfficeSize.value?a.qnaOfficeSize.value.search(/^[0-9]*$/)&&(c="<p>매장 또는 사무실 규모는 숫자로만 입력해 주시기 바랍니다.</p>",a.qnaOfficeSize.select()):c="<p>매장 또는 사무실 규모를 입력해 주시기 바랍니다.</p>",o=a.qnaOfficeSize,alertCom(o,c)):(c="<p>분류 항목을 선택해 주시기 바랍니다.</p>",o=a.qnaDivSort,alertCom(o,c)):(c="<p>올바른 이메일 형식이 아닙니다.</p>",o=$(".writeEmail").is(":visible")?
a.qnaWriteEmail:a.qnaEmail,alertCom(o,c)):(c="<p>고객님의 이메일 도메인을 선택해 주시기 바랍니다.</p>",o=a.qnaDomain,alertCom(o,c)):(c="<p>고객님의 이메일 계정을 입력해 주시기 바랍니다.</p>",o=a.qnaEmail,alertCom(o,c)):(c="<p>고객님의 이메일 도메인을 입력해 주시기 바랍니다.</p>",o=a.qnaWriteDomain,alertCom(o,c)):(c="<p>고객님의 이메일계정을 입력해 주시기 바랍니다.</p>",o=a.qnaWriteEmail,alertCom(o,c)):(c="<p>고객님의 이름을 입력해 주시기 바랍니다.</p>",o=a.qnaName,alertCom(o,c)))}
function isCaptchaValidCheck(t){var e="https://"+window.location.host+"/aemapi/business/common/captchacheck",a=!0,n={};return n.captchaAns=t,n.captchaCookieCode="SEC-CON",$.ajax({type:"post",url:e,data:n,async:!1,xhrFields:{withCredentials:!0},dataType:"json",success:function(t){"304"==t.response.statusCode&&(a=!1),$(".contact-layer .btn-refresh").trigger("click")},error:function(){a=!1}}),a}
$(function(){$(".s-login_new button").on("mouseenter focus",function(){$(".gb-gnb__my-layer").show()}),$(".gb-gnb__my-layer").on("mouseleave",function(){$(this).hide()}),$(".gb-gnb__my-layer a").on("focusout",function(){$(this).parent().index()===$(".gb-gnb__my-layer a").length-1&&$(".gb-gnb__my-layer").hide()})}),$(".multiple_list").on("click","button",function(){var t=$(this),e=t.index();t.toggleClass("on"),t.closest(".td").find('[class*="AddTableList"] .addList tr').eq(e).toggleClass("on")}),$(".addList").on("click",
"tr",function(t){t.stopImmediatePropagation();var e=$(this),a=e.index();e.toggleClass("on"),e.closest(".td").find(".multiple_list button").eq(a).toggleClass("on")});var networkErrorCnt=0;
$("#contactDomain, #letterDomain, #qnaDomain").on("change",function(){var t=$(this),e=t.closest(".row").find('input[type="text"]'),a=e.val();"etc"===t.val()?(t.closest(".row").next(".writeEmail").show().find('input[type="text"]').eq(0).focus().val(a),e.prop("disabled",!0).val("")):(t.closest(".row").next(".writeEmail").hide(),e.prop("disabled",!1))}),$("#qnaDivSort").on("change",function(){var t=$("#partner-login-msg"),e=t.find(".txt"),a=t.find("button"),n=$(this);if("QNA22"===n.val()){var o=$("#secdevdomain").val()+
"/Member/LoginCheck.aspx";$.ajax({url:o,type:"GET",xhrFields:{withCredentials:!0},dataType:"jsonp",jsonp:"callback",async:!1,success:function(n){var o=n.B2BLoginYN;"N"==o?($("#qnaDivSort").val(""),$("#qnaDivSort").trigger("change"),t.addClass("on"),e.text('"파트너(판매점) 신청" 문의는 로그인 후 가능합니다.'),a.text("로그인").off("click").on("click",function(){window.location.href="https://account.samsung.com/account/check.do"})):"A"==o?($("#qnaDivSort").val(""),$("#qnaDivSort").trigger("change"),t.addClass("on"),e.text('"파트너(판매점) 신청" 비즈니스 회원만 가능합니다.'),
a.text("회원가입").off("click").on("click",function(){window.location.href="https://www.samsung.com/sec/business/support/member/regular-signup/"})):"R"==o&&($("#partnerArea1").show(),$("#partnerArea2").show())},error:function(){closeAlert("<p>잠시 후 다시 시도해주세요.</p>")}})}else $("#partnerArea1").hide(),$("#partnerArea2").hide(),t.removeClass("on")}),$('input[name="rdoPath"], input[name="contactRa"]').change(function(){var t=$(this);"WPT00"==t.val()?t.parent().find('input[type="text"]').prop("disabled",!1).focus():
$('input[name*="TxtPath"]').prop("disabled",!0).val("")}),$("#contactAgreeAll, #qnaAgreeAll").change(function(){var t=$(this),e=t.parent().next().find('input[type="checkbox"]');t.is(":checked")?e.prop("checked",!0):e.prop("checked",!1)}),$("#contactAgreeAll, #qnaAgreeAll").parent().next().find('input[type="checkbox"]').change(function(){var t=$(this),e=t.closest(".clause").prev().find('input[type="checkbox"]'),a=t.is(":checked");e.parent().next().find('input[type="checkbox"]').each(function(){$(this).is(":checked")||
(a=!1)}),e.prop("checked",a)}),$(document).on("click","#companyList > tr > td > button",function(){var t=$(this).text(),e=$(this).parent().next().text().replace(/-/g,"");$("#letterComName").val(t),$("#contactComName").val(t),$("#letterComNum").val(e),$("#contactComNum").val(e),$(".pop_layer").hide(),$(".contact-layer").removeClass("comSearchOn")}),$(function(){$(".posWrap .pop_click").on("click",function(){var t=$(this);t.closest(".posWrap").find(".estimate_pop").show()}),$(".posWrap .btn_pop_clse2").on("click",
function(){return $(".estimate_pop").hide(),!1}),$(".posWrap .btn_area a").on("click",function(){return $(".estimate_pop").hide(),contactOpen(0),!1})});
